import {installPromptTemplates} from './shared/prompt-templates.mjs';
import {notebookBrowser} from './notebook-browser.mjs';
import {installModePicker,resolveMode,materialPreview} from './shared/material-browser.mjs';
/* SPDX-License-Identifier: AGPL-3.0-or-later */
import {TYPES} from './shared/material-catalog.mjs';
const E=window.parent.Zotero.Research,N=E.notebook,A=E.manuscripts,id=window.frameElement.projectID,$=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
let browser;let composing=false,timer,controller,selectedRendered=null,editing=false;
function status(text){$('status').textContent=text;}
function button(text,fn,host){const b=el('button',text);b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(e=>status(e.message));host.append(b);return b;}
function rich(host,text,sources=[]){const n=el('div');E.renderContent(n,text,{sources,onSource:s=>N.openSource(s)});host.append(n);return n;}
function tab(plan){$('reading').hidden=plan;$('evaluation').hidden=!plan;$('read-tab').setAttribute('aria-selected',String(!plan));$('plan-tab').setAttribute('aria-selected',String(plan));document.body.classList.toggle('plan-view',plan);N.update(id,{view:plan?'plan':'read'});}
async function run(fn){if(controller)return;controller=new AbortController();$('cancel').hidden=false;$('evaluate').disabled=true;try{await fn(controller.signal);status('已保存到本机');render();}catch(e){window.parent.Zotero.logError(e);status(e.message+'；已有素材与方案保留。');}finally{controller=null;$('cancel').hidden=true;$('evaluate').disabled=false;}}
function sourceEvidence(host,m){const raw=el('details');raw.append(el('summary','原文证据'));const quote=el('blockquote',m.sourceText);quote.className='source-quote';raw.append(quote);host.append(raw);}
function detail(m){
 if(editing)return;selectedRendered=m?m.id+':'+m.revision:null;const host=$('detail');host.className='';host.replaceChildren();
 if(!m){host.append(el('p','选择素材查看原文与中文说明。'));return;}
 host.append(el('h2',A.titleFor(m)));materialPreview(host,m,E);
 if(m.id.startsWith('passage-')&&!A.assetLibrary()[m.id]){
  host.append(el('p',E.materialSourceInfo(m).title),el('small','论文全文命中 · 第 '+((m.pageIndex??0)+1)+' 页'));
  rich(host,A.summaryFor(m));
  const actions=el('div');actions.className='source-actions';
  button('保存到素材库',()=>N.savePassage(id,m),actions).className='primary';button('打开原文',()=>N.openSource({anchor:m.anchor}),actions);
  host.append(actions);sourceEvidence(host,m);return;
 }
 const ctx=el('label'),check=el('input');check.type='checkbox';check.checked=N.contextMode(id,m)!=='off';check.onchange=()=>N.setContext(id,m,check.checked);ctx.append(check,document.createTextNode('用于来源问答'));host.append(ctx);
 rich(host,A.summaryFor(m));host.append(el('small',m.kind==='abstract'?'仅依据摘要':m.imagePath?'图片原件 · AI 解读待核验':m.kind==='idea'?'研究构想或实验计划，待验证':'来源摘录 · 第 '+((m.pageIndex??m.anchor?.pageIndex??0)+1)+' 页'));
 const actions=el('div');actions.className='source-actions';button('打开来源',()=>N.openSource({materialID:m.id,anchor:m.anchor,url:m.anchor?.url}),actions);
 button('编辑中文说明',()=>{editing=true;const input=el('textarea');input.value=A.summaryFor(m);host.append(input);input.focus();button('保存说明',async()=>{await A.editAsset(m.assetID||m.id,{summary:input.value},m.revision);editing=false;selectedRendered=null;render();},host);button('取消编辑',()=>{editing=false;detail(m);},host);},actions);
 if(m.imagePath)button(m.generationStatus==='failed'?'重试中文图片说明':'AI 解释图片',()=>run(signal=>N.describeImage(id,m.id,status,signal)),actions);
 host.append(actions);if(m.generationError)host.append(el('p',m.generationError));sourceEvidence(host,m);
}
function libraryHome(){document.getElementById('library-manager')?.remove();const dialog=el('dialog');dialog.id='library-manager';dialog.append(el('h2','所有素材与研究主题'));button('关闭',()=>dialog.close(),dialog);button('浏览全部素材',async()=>{await N.catalog(id,p=>{p.ui.catalog={topic:'',type:'',sort:'relevance',selection:[]};});await N.update(id,{query:'',selectedMaterial:null,view:'read'});$('search').value='';tab(false);dialog.close();},dialog);const projects=el('div');projects.className='library-projects';for(const p of Object.values(A.all())){const row=el('article');row.append(el('strong',p.title),el('small',p.materials.length+' 张项目关联素材'));button('打开项目素材',async()=>{await N.update(p.id,{view:'read'});await N.open(p.id);dialog.close();},row);projects.append(row);}dialog.append(projects);document.body.append(dialog);dialog.showModal();}
 $('library-home').onclick=libraryHome;
 function render(){const state=N.state(id),project=N.project(id);if(!project)return;const materials=N.materials(id),selected=materials.find(m=>m.id===state.selectedMaterial)||N.passageResults(id).find(r=>r.m.id===state.selectedMaterial)?.m,results=N.results(id),list=$('source-list');$('title').textContent=project.title+(state.view==='plan'?' · 可行性与实验':' · 素材库');document.body.classList.toggle('plan-view',state.view==='plan');$('read-tab').setAttribute('aria-selected',String(state.view!=='plan'));$('plan-tab').setAttribute('aria-selected',String(state.view==='plan'));$('count').textContent=materials.length+' 张';if(document.activeElement!==$('search')&&!composing)$('search').value=state.query||'';const type=project.ui.catalog?.type||'';$('type').value=type;browser?.render();
 const discussion=$('plan-discussion');discussion.replaceChildren(el('h3','讨论与修改记录'));for(const turn of state.messages.filter(m=>!m.channel)){const row=el('div');row.className='plan-discussion-turn';row.append(el('small',turn.role==='user'?'研究者 · 观点与修改要求':'AI · 方案摘要'));rich(row,turn.text,turn.sources||[]);discussion.append(row);}const assessment=state.assessment;$('assessment-status').textContent=assessment?.message||'先明确研究问题，再核对证据与实验条件。';$('evaluate').textContent=assessment?.status==='failed'?'重试可行性评估':state.versions.length?'更新可行性与实验方案':'评估并制定实验方案';
 if(selectedRendered!==(selected?selected.id+':'+selected.revision:null)||!$('detail').children.length)detail(selected);
 const messages=$('messages');messages.replaceChildren();for(const c of state.messages.filter(c=>c.channel==='source'&&c.contextID===(state.selectedMaterial||'library'))){const row=el('div');row.className='message';row.append(el('small',c.role==='user'?'你':'AI · 根据来源'));rich(row,c.text,c.sources||[]);if(c.evidence?.length){const evidence=el('details');evidence.append(el('summary','原文证据 · '+c.evidence.length+' 条'));for(const ev of c.evidence){const source=c.sources?.find(s=>s.id===ev.sourceID);if(!source)continue;button('定位原文 · '+source.title,()=>N.openSource(source),evidence).className='source-citation';evidence.append(el('blockquote',ev.quote));}row.append(evidence);}messages.append(row);}
 const artifacts=$('artifact-list');artifacts.replaceChildren();for(const a of state.artifacts){const m=materials.find(m=>m.id===a.materialID),card=el('div',m?.title||'研究方案');card.className='artifact';card.dataset.material=a.materialID;card.tabIndex=0;card.draggable=true;card.ondragstart=e=>e.dataTransfer.setData('application/x-manuscript-material',a.materialID);card.append(el('small',(a.status==='needs-review'?'需重新核验':'已确认')+' · 实验计划 · 拖入写作'));if(a.reviewReason)card.append(el('small',a.reviewReason));button('查看方案',()=>{N.update(id,{selectedVersion:a.versionID});tab(true);},card);artifacts.append(card);}if(!state.artifacts.length)artifacts.append(el('p','确认评估方案后，产物会保存在这里。'));
 const versions=$('versions');versions.replaceChildren();for(const v of [...state.versions].reverse())button(`第 ${v.number} 版 · ${v.status==='confirmed'?'已确认':'待审阅'}`,()=>{N.update(id,{selectedVersion:v.id});tab(true);},versions).className='version';
 $('decisions').replaceChildren();for(const d of state.decisions)rich($('decisions'),`**决定**：${d.decision}\n\n原因：${d.reason}\n\n反对意见：${d.objection||'尚未记录'}`);
 const v=state.versions.find(v=>v.id===state.selectedVersion)||state.versions.at(-1),plan=$('plan');plan.replaceChildren();if(v){if(!v.sources.some(s=>s.url))plan.append(Object.assign(el('p','本版联网未取得可读摘要，评估仅依据本地材料；创新性尚未完成外部核验。'),{className:'warning'}));if(N.stale(v).length)plan.append(Object.assign(el('p','相关来源已更新，此版本需要重新核验；正文和旧方案保留。'),{className:'warning'}));const overview=el('div');overview.className='assessment-overview';for(const [key,label] of [['novelty','创新性依据'],['feasibility','可行性与限制'],['minimumValidation','先做什么实验']]){const section=el('section');section.append(el('h3',label));rich(section,N.presentPlan(v)[key],v.sources);overview.append(section);}plan.append(overview);if(v.plan.pending.length){const pending=el('details');pending.append(el('summary','待补条件 · '+v.plan.pending.length+' 项'));for(const item of v.plan.pending)pending.append(el('p',item));plan.append(pending);}if(v.status!=='confirmed')button('确认并保存为研究产物',()=>N.confirm(id,v.id),plan).className='primary';const literature=el('section');literature.className='closest-literature';literature.append(el('h3','最接近工作与反证'));for(const work of v.plan.closest){const src=v.sources.find(s=>s.id===work.sourceID);if(!src)continue;const card=el('article');button(src.title,()=>N.openSource(src),card);const metric=src.metric;card.append(el('small',[src.year,src.journal,metric?.impact_factor!=null?'IF '+metric.impact_factor+(metric.metric_year?'（'+metric.metric_year+'）':''):'',src.coverage].filter(Boolean).join(' · ')));rich(card,'差异：'+work.difference+'\n\n反证或限制：'+work.counterevidence,v.sources);literature.append(card);}plan.append(literature);
 const full=el('details');full.append(el('summary','完整实验方案、接近工作与原文证据'));rich(full,N.planMarkdown(v),v.sources);plan.append(full);const change=el('details');change.append(el('summary','本版影响范围'),el('p','相关假设：'+(v.changedHypotheses.join('、')||'无')+'；待复核实验：'+(v.affectedExperiments.join('、')||'无')));plan.append(change);$('logs').replaceChildren();for(const r of v.retrieval)$('logs').append(el('p',r.query+' · '+r.provider+' · '+(r.error||r.count+' 条')));}
}
$('search').addEventListener('compositionstart',()=>{composing=true;clearTimeout(timer);});function query(){clearTimeout(timer);timer=setTimeout(()=>N.update(id,{query:$('search').value}),180);}$('search').addEventListener('compositionend',()=>{composing=false;query();});$('search').oninput=()=>{if(!composing)query();};
for(const t of ['',...TYPES]){const option=el('option',t||'全部类型');option.value=t;$('type').append(option);}$('type').onchange=()=>N.catalog(id,p=>{p.ui.catalog||={topic:id,selection:[],sort:'relevance'};p.ui.catalog.type=$('type').value;p.ui.catalog.categoryID=null;});
$('read-tab').onclick=()=>tab(false);$('plan-tab').onclick=()=>tab(true);$('back').onclick=async()=>{await N.catalog(id,p=>{p.researchGoal=N.state(id).ideaDraft||p.researchGoal;p.memory||={};p.memory.goal=p.researchGoal;});await N.update(id,{workflowStage:'assembly',aiMode:'auto'});await A.open(id);};$('cancel').onclick=()=>controller?.abort();window.addEventListener('keydown',e=>{if(e.key==='Escape')controller?.abort();});
$('question-form').onsubmit=e=>{e.preventDefault();const q=$('question').value.trim();if(!q)return;run(async signal=>{const mode=resolveMode($('ai-mode').value,q);if(mode==='search'){await N.update(id,{query:q});$('search').value=q;await N.rememberQuery(id,q);await browser.findOnline();return;}if(mode==='evaluate'){await N.update(id,{ideaDraft:q,view:'plan'});$('idea').value=q;tab(true);await N.evaluate(id,q,status,signal);return;}if(mode==='write'){await N.update(id,{writingPrompt:q});await A.open(id);const manuscript=window.parent.document.getElementById('manuscript-'+id)?.contentWindow;const ui=manuscript?.ManuscriptUI;if(ui?.ready){ui.p.ui.aiOpen=true;ui.$('ai').hidden=false;ui.$('ai-prompt').value=q;ui.$('ai-mode').value='write';ui.$('ai-prompt').focus();await N.update(id,{writingPrompt:''});}return;}const preview=el('div');preview.className='message';$('messages').append(preview);try{await N.ask(id,q,status,signal,text=>{E.renderContent(preview,text);status('正在回答 · 引用核验完成后保存');});}finally{preview.remove();}$('question').value='';await N.update(id,{questionDraft:''});});};
async function startAssessment(){return run(async signal=>{await N.update(id,{ideaDraft:$('idea').value,constraints:$('constraints').value,assessment:{status:'running',message:'正在检索接近工作与可行性条件'}});try{const v=await N.evaluate(id,$('idea').value,status,signal);await N.update(id,{assessment:{status:'ready',versionID:v.id,message:'已形成待审阅的可行性与实验方案'}});}catch(error){await N.update(id,{assessment:{status:'failed',message:error.message}});throw error;}});}
$('evaluate').onclick=startAssessment;
const discussion=$('plan-discussion');discussion.append(el('h3','继续完善观点'),el('p','在上方补充新的条件、质疑或修改目标，更新方案会保留此前版本。'));
for(const [element,key] of [['idea','ideaDraft'],['question','questionDraft'],['constraints','constraints']]){$(element).value=N.state(id)[key]||'';let draftTimer;const saveDraft=()=>{clearTimeout(draftTimer);N.update(id,{[key]:$(element).value});};$(element).oninput=()=>{clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,500);};$(element).onchange=saveDraft;window.addEventListener('pagehide',saveDraft);}
browser=notebookBrowser({E,N,A,id,$,el,button,status,run});installModePicker($('ai-mode'),$('question'),{value:N.state(id).aiMode,onChange:aiMode=>N.update(id,{aiMode})});
installPromptTemplates(document,E);const unsubscribe=N.subscribe(projectID=>{if(projectID===id)render();}),assets=A.onAssetsChanged(()=>{selectedRendered=null;render();});const dispose=()=>{unsubscribe();assets();controller?.abort();};window.addEventListener('pagehide',dispose);
$('reading').hidden=N.state(id).view==='plan';$('evaluation').hidden=N.state(id).view!=='plan';render();status('素材、来源选择、讨论和方案版本已恢复');window.NotebookUI={ready:true,render,N,id,dispose,browser,startAssessment};

$('project-stage-name').onclick=()=>E.openWorkflow('writing');$('project-stage-plan').onclick=()=>{$('idea').focus();};$('project-stage-assembly').onclick=()=>$('back').click();
