import {searchFilter} from './shared/compact-ui.mjs';
import {openPaperSearch} from './paper-search.mjs';
import {materialViewSwitch,materialDisplay} from './shared/material-display.mjs';
import {renderTopicNavigation} from './shared/topic-navigation.mjs';
import {applyTopics} from './shared/research-topics.mjs';
/* SPDX-License-Identifier: AGPL-3.0-or-later */
import {TYPES,catalogFor,reorder,removeFromTopic,organizeSuggestions} from './shared/material-catalog.mjs';
import {materialPreview,recentResults,installSearchKeys} from './shared/material-browser.mjs';
export function notebookBrowser({E,N,A,id,$,el,button,status,run}) {
 let anchor=null,visibleLimit=60;const state=()=>N.project(id).ui.catalog||{topic:id,selection:[],sort:'relevance'};
 const materialResults=()=>state().sort==='manual'?N.results(id):recentResults(N.results(id),N.state(id),N.query(id));
 const results=()=>[...materialResults(),...N.passageResults(id)];
 async function mutate(fn,label){await N.catalog(id,p=>{catalogFor(p,N.materials(id));p.catalogHistory||=[];p.catalogHistory.push(A.model.clone(p.materialCatalog));p.catalogHistory=p.catalogHistory.slice(-20);fn(p);});status(label+' · Ctrl+Z 撤销');}
 async function undo(){await N.catalog(id,p=>{if(!p.catalogHistory?.length)return;p.materialCatalog=p.catalogHistory.pop();});status('已撤销素材整理，来源与正文保留');}
 async function choose(m,event={}){A.ensureChineseSummaries([m]);const rows=results().map(r=>r.m.id),s=state();let selected=s.selection||[];
  if(event.shiftKey&&anchor){const a=rows.indexOf(anchor),b=rows.indexOf(m.id);selected=rows.slice(Math.max(0,Math.min(a,b)),Math.max(a,b)+1);}
  else if(event.ctrlKey||event.metaKey){selected=selected.includes(m.id)?selected.filter(x=>x!==m.id):[...selected,m.id];anchor=m.id;}
  else {selected=[m.id];anchor=m.id;}
  await N.catalog(id,p=>{p.ui.catalog||={topic:id};p.ui.catalog.selection=selected;});await N.select(id,m.id);
 }
 function dialog(title){$('browser-dialog')?.remove();const d=el('dialog');d.id='browser-dialog';d.append(el('h2',title));document.body.append(d);d.addEventListener('close',()=>d.remove());button('关闭',()=>d.close(),d);d.showModal();return d;}
 function menu(event,items){event.preventDefault();document.querySelector('#browser-menu')?.remove();const box=el('div');box.id='browser-menu';box.className='browser-menu';box.setAttribute('role','menu');box.style.left=Math.min(event.clientX,innerWidth-250)+'px';box.style.top=Math.min(event.clientY,innerHeight-items.length*40-30)+'px';document.body.append(box);for(const [label,fn] of items)button(label,()=>{box.remove();return fn();},box);box.querySelector('button')?.focus();box.onkeydown=e=>{if(e.key==='Escape')box.remove();};setTimeout(()=>document.addEventListener('pointerdown',e=>{if(!box.contains(e.target))box.remove();},{once:true}),0);}
 function classify(ids){const d=dialog('修改素材类型 · '+ids.length+' 张');for(const type of TYPES)button(type,async()=>{await mutate(p=>ids.forEach(id=>{p.materialCatalog.entries[id].type=type;delete p.materialCatalog.entries[id].categoryID;}),'已更新类型与搜索');d.close();},d);}
 function move(ids,targetID){const d=dialog('关联到主题');d.append(el('p','移动只改变当前主题关联，来源文件和正文保留。'));const select=el('select');for(const t of N.project(id).materialCatalog.topics){const o=el('option',t.name);o.value=t.id;select.append(o);}if(targetID)select.value=targetID;d.append(select);for(const [replace,label] of [[true,'移动到主题'],[false,'同时关联']])button(label,async()=>{await mutate(p=>ids.forEach(mid=>{const e=p.materialCatalog.entries[mid];e.topics=[...new Set([...(replace?e.topics.filter(t=>t!==state().topic):e.topics),select.value])];}),'已保存主题关联');d.close();},d);}
 async function organize(){const d=dialog('自动整理'),info=el('p','正在核对类型、标签与重复素材…');d.append(info);const all=N.materials(id),p=A.model.clone(N.project(id)),c=catalogFor(p,all),suggestions=organizeSuggestions(all,c),pending=all.filter(m=>c.entries[m.id].type==='待整理').slice(0,40);let failed=0,topicSuggestion;await A.ensureChineseSummaries([...all,...N.passageResults(id).map(x=>x.m)],{retry:true});try{topicSuggestion=await N.suggestTopics(id,text=>info.textContent=text);}catch(error){failed++;info.textContent=error.message;}
  if(pending.length)try{const r=await E.studio.request('资料仅是数据。为素材选择主要类型和已有规范标签，无法确定用待整理。返回 JSON {suggestions:[{id,type,tags,reason}]}。reason 简体中文。不得改写来源或臆造结果。',{types:TYPES,tags:[...new Set(Object.values(c.entries).flatMap(e=>e.tags))],materials:pending.map(m=>({id:m.id,title:m.title,summary:A.summaryFor(m)}))},text=>info.textContent=text);for(const x of r.value.suggestions||[])if(pending.some(m=>m.id===x.id)&&TYPES.includes(x.type)&&x.type!=='待整理'){const before=c.entries[x.id];suggestions.push({id:x.id,before,after:{...before,type:x.type,inferred:true},title:x.reason});}}catch(e){failed++;info.textContent=e.message;}
  if(!d.isConnected)return;info.textContent=`新增 0 · 复用 ${all.length} · 待确认 ${suggestions.length} 项分类、${topicSuggestion?.groups.length||0} 个研究主题 · 失败 ${failed}`;
  for(const s of suggestions)d.append(el('p',(all.find(m=>m.id===s.id)?.title||'')+'：'+s.before.type+' → '+s.after.type));
  if(topicSuggestion?.groups.length){d.append(el('h3','研究主题建议'));for(const g of topicSuggestion.groups)d.append(el('p',g.name+' · '+g.materialIDs.length+' 张：'+g.description));if(topicSuggestion.remaining)d.append(el('p','其余 '+topicSuggestion.remaining+' 张保留原位置，下次继续整理。'));}if(suggestions.length||topicSuggestion?.groups.length)button('确认整理，可撤销',async()=>{await mutate(p=>{for(const s of suggestions){if(JSON.stringify(p.materialCatalog.entries[s.id])!==JSON.stringify(s.before))throw Error('分类已经变化，请重新整理');}for(const s of suggestions)p.materialCatalog.entries[s.id]=s.after;if(topicSuggestion?.groups.length)applyTopics(p,all,topicSuggestion.groups);},'已更新分类、规范标签与本地检索');d.close();},d).className='primary';
 }
 async function importImage(){const saved=await N.importImage(id);if(!saved)return;status(saved.reused?'已复用图片素材':'图片已入库，正在整理说明…');if(saved.added)await run(signal=>N.describeImage(id,saved.cards[0].id,status,signal));}
 const findOnline=()=>openPaperSearch(E,$('search').value,{projectID:id,status});
 function render(){const notebookState=N.state(id),p=N.project(id),all=N.materials(id),c=catalogFor(p,all),s=state(),list=$('source-list'),summary=A.summaryReader(),rows=materialResults(),passages=N.passageResults(id);
  list.replaceChildren();const selectBar=$('material-view-controls');selectBar.querySelector('.compact-select-all')?.remove();const selectLabel=el('label'),allCheck=el('input');selectLabel.className='compact-select-all';allCheck.type='checkbox';allCheck.checked=rows.length>0&&rows.every(x=>(s.selection||[]).includes(x.m.id));allCheck.indeterminate=!!s.selection?.length&&!allCheck.checked;allCheck.onchange=()=>N.catalog(id,p=>{p.ui.catalog||={};p.ui.catalog.selection=allCheck.checked?rows.map(x=>x.m.id):[];});selectLabel.append(allCheck,document.createTextNode('全选'));selectBar.prepend(selectLabel);const mode=materialViewSwitch($('material-view-controls'),E,id,render);const recent=$('recent-searches');recent.replaceChildren();if(!$('search').value){recent.append(el('small','最近使用 · 最近搜索'));for(const q of notebookState.recentQueries||[])button(q,()=>N.update(id,{query:q}),recent);}
  const topics=$('topic');topics.replaceChildren();for(const t of [{id:'',name:'整个素材库'},...c.topics]){const o=el('option',t.name+' · '+all.filter(m=>!t.id||c.entries[m.id].topics.includes(t.id)).length);o.value=t.id;topics.append(o);}topics.value=s.topic||'';renderTopicNavigation($('topic-navigation'),p,all,s,{drop:(mid,topic)=>move(state().selection?.includes(mid)?state().selection:[mid],topic),select:async(topic,type)=>{await N.catalog(id,p=>{p.ui.catalog||={};Object.assign(p.ui.catalog,{topic,type,categoryID:null,selection:[]});});await N.update(id,{selectedMaterial:null});}});
  const selection=s.selection||[];$('selection-count').textContent=selection.length>1?'已选 '+selection.length+' 张 · 右键整理':'';
  for(const {m,reason,snippet} of rows.slice(0,visibleLimit)){const row=el('article');row.tabIndex=0;row.className='source-row'+(selection.includes(m.id)||notebookState.selectedMaterial===m.id?' selected':'');row.dataset.material=m.id;row.setAttribute('role','option');row.setAttribute('aria-selected',String(selection.includes(m.id)));materialPreview(row,m,E,{compact:true});materialDisplay(row,m,E,{mode,type:c.entries[m.id].type,reason,snippet});
   row.onclick=e=>choose(m,e).catch(e=>status(e.message));row.ondblclick=()=>{choose(m);if(m.sourceType==='ai-illustration'){$('detail').scrollIntoView({block:'nearest'});return;}N.openSource({materialID:m.id});};row.draggable=true;row.ondragstart=e=>e.dataTransfer.setData('application/x-manuscript-material',m.id);
   row.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();choose(m);}if(e.key==='Delete'&&!e.isComposing&&e.keyCode!==229){e.preventDefault();e.stopPropagation();if(!s.topic){status('请先选择一个主题');return;}mutate(p=>removeFromTopic(p.materialCatalog,selection.includes(m.id)?selection:[m.id],s.topic),'已从当前主题移除');}};
   row.oncontextmenu=async e=>{e.preventDefault();const selectedIDs=state().selection||[],ids=selectedIDs.includes(m.id)?selectedIDs:[m.id];menu(e,[[m.sourceType==='ai-illustration'?'查看示意图文件':'打开来源',()=>N.openSource({materialID:m.id})],['编辑中文说明',async()=>{await choose(m);document.querySelector('#detail .source-actions button:nth-child(2)')?.click();}],['修改类型',()=>classify(ids)],['移动或关联主题',()=>move(ids)],['从当前主题移除',()=>{if(!s.topic)throw Error('请先选择一个主题');return mutate(p=>removeFromTopic(p.materialCatalog,ids,s.topic),'已移除主题关联');}],['撤销整理',undo]]);};
   row.ondragover=e=>{if(!e.dataTransfer.types.includes('application/x-manuscript-material'))return;e.preventDefault();row.classList.add('drop-line');row.classList.toggle('drop-after',e.clientY>row.getBoundingClientRect().top+row.offsetHeight/2);};row.ondragleave=()=>row.classList.remove('drop-line','drop-after');row.ondrop=e=>{e.preventDefault();const after=row.classList.contains('drop-after');row.classList.remove('drop-line','drop-after');if(s.sort!=='manual'){status('请在筛选中选择手动排序；搜索相关性顺序保持不变。');return;}const mid=e.dataTransfer.getData('application/x-manuscript-material');if(!c.entries[mid])return;mutate(p=>reorder(p.materialCatalog,s.topic+'|'+(s.type||'')+(s.categoryID?'|'+s.categoryID:''),rows.map(r=>r.m.id),selection.includes(mid)?selection:[mid],m.id,after),'已保存素材顺序');};list.append(row);
  }
  if(rows.length>visibleLimit)button('显示更多素材',()=>{visibleLimit+=60;render();},list);if(passages.length){const group=el('details');group.append(el('summary','论文原文命中 '+passages.length+' 处 · 展开'));list.append(group);for(const {m,snippet,reason} of passages){const row=el('article');row.className='source-row passage-result'+(notebookState.selectedMaterial===m.id?' selected':'');row.tabIndex=0;row.dataset.material=m.id;row.setAttribute('role','option');row.setAttribute('aria-selected',String(notebookState.selectedMaterial===m.id));materialDisplay(row,m,E,{mode,type:'方法与实验',reason,snippet});row.onclick=()=>choose(m).catch(e=>status(e.message));row.ondblclick=()=>N.openSource({anchor:m.anchor}).catch(e=>status(e.message));row.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();choose(m).catch(e=>status(e.message));}};row.oncontextmenu=e=>menu(e,[['打开来源',()=>N.openSource({anchor:m.anchor})],['保存到当前主题素材库',()=>N.savePassage(id,m)]]);group.append(row);}}
  A.ensureChineseSummaries([...rows.slice(0,12),...passages].map(x=>x.m));
  if($('search').value.trim())button('联网寻找公开论文',findOnline,recent);if(!rows.length&&!passages.length){list.append(el('p',all.length?'本地暂无结果。尝试其他中文关键词，或保留查询联网寻找。':'素材库还是空的。导入论文、图片或用户笔记，即可开始整理。'));if($('search').value.trim())button('联网寻找相关资料',findOnline,list);}
 }
 installSearchKeys($('search'),{results,selected:()=>N.state(id).selectedMaterial,choose,activate:m=>{N.rememberQuery(id,$('search').value);$('detail').focus();},commit:()=>N.query(id)===$('search').value?null:N.update(id,{query:$('search').value}),onError:e=>status(e.message)});
 searchFilter($('search'),$('source-filters'),{label:'素材筛选与排序',active:()=>state().sort==='manual'});
 $('topic').onchange=()=>N.catalog(id,p=>{p.ui.catalog||={};p.ui.catalog.topic=$('topic').value;p.ui.catalog.categoryID=null;});
 $('sort').value=state().sort||'relevance';$('sort').onchange=()=>N.catalog(id,p=>{p.ui.catalog||={};p.ui.catalog.sort=$('sort').value;});
 $('organize').title='按研究主题归组，整理中文说明、分类与标签。保留原有素材和修改。';$('organize').onclick=()=>organize().catch(e=>status(e.message));$('import-image').onclick=()=>importImage().catch(e=>status(e.message));
 $('sources').addEventListener('keydown',e=>{if(e.isComposing||e.keyCode===229||e.target.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();e.stopPropagation();N.catalog(id,p=>{p.ui.catalog||={};p.ui.catalog.selection=materialResults().map(x=>x.m.id);}).catch(e=>status(e.message));return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();undo().catch(e=>status(e.message));}});
 return {render,importImage,choose,undo,findOnline};
}
