import test from 'node:test';import assert from 'node:assert/strict';
import {validatePlan,changedHypotheses,affectedExperiments} from '../../../chrome/content/zotero/research/shared/academic-plan.mjs';
import {catalogFor,catalogResults} from '../../../chrome/content/zotero/research/shared/material-catalog.mjs';
import {partialText} from '../../../chrome/content/zotero/research/shared/json-stream.mjs';
test('streamed JSON exposes only decoded prose and tolerates split UTF-8 escapes',()=>{assert.equal(partialText('{"text":"中文\\n**说明'), '中文\n**说明');assert.equal(partialText('{"text":"数学 $\\\\alpha$"'), '数学 $\\alpha$');assert.equal(partialText('{"text":"字\\u4e'), '字');assert.equal(partialText('{"text":"字\\u4e2d'), '字中');assert.equal(partialText('{"evidence":[]'), '');});
test('academic plan cannot cite invented sources or omit falsification; missing resources remain pending',()=>{const value={hypotheses:[{id:'h1',claim:'方法可能改善迁移',falsification:'独立域无增益'}],closest:[{sourceID:'s1',quote:'Actual evidence'}],experiments:[{id:'e1',hypothesisID:'h1'}]};const sources=[{id:'s1',text:'Actual evidence about data',coverage:'仅依据摘要'}],plan=validatePlan(value,sources);assert.equal(plan.experiments[0].status,'planned');assert.equal(plan.experiments[0].leakage,'待补');assert.ok(plan.pending.length>10);assert.equal(plan.closest[0].coverage,'仅依据摘要');assert.throws(()=>validatePlan(value,[]),/未检索/);assert.throws(()=>validatePlan({...value,closest:[{sourceID:'s1',quote:'invented quote'}]},sources),/未匹配/);assert.throws(()=>validatePlan({...value,hypotheses:[{id:'h1',claim:'not falsifiable'}]},sources),/否定条件/);});
test('hypothesis changes only mark dependent experiments; old plan remains immutable',()=>{const old={hypotheses:[{id:'h1',claim:'A'},{id:'h2',claim:'B'}]},next={hypotheses:[{id:'h1',claim:'C'},{id:'h2',claim:'B'}],experiments:[{id:'e1',hypothesisID:'h1'},{id:'e2',hypothesisID:'h2'}]};assert.deepEqual(changedHypotheses(old,next),['h1']);assert.deepEqual(affectedExperiments(next,['h1']),['e1']);assert.equal(old.hypotheses[0].claim,'A');});
test('compact and expanded catalog share Chinese alias query, filters and persisted manual order',()=>{const all=[{id:'m1',title:'CNN',category:'方法'},{id:'m2',title:'卷积神经网络',category:'方法'},{id:'m3',title:'CNN局限',category:'局限'}],p={id:'p',title:'项目'};catalogFor(p,all);p.materialCatalog.orders['p|方法']=['m2','m1'];const hits=catalogResults(all,'卷积神经网络',p,{topic:'p',type:'方法',sort:'manual'});assert.deepEqual(hits.map(h=>h.m.id),['m2','m1']);assert.equal(all.length,3);});

import {bindPlanCitations} from '../../../chrome/content/zotero/research/shared/academic-plan.mjs';
test('temporary model quote numbers resolve to stable sources without changing raw quotations or saved versions',()=>{const p={novelty:'有先行工作 [Q1]',closest:[{quote:'The original [Q1]',difference:'见 [Q2]'}]};const bound=bindPlanCitations(p,[{id:'asset-real'}]);assert.equal(bound.novelty,'有先行工作 [asset-real]');assert.equal(bound.closest[0].quote,'The original [Q1]');assert.match(bound.closest[0].difference,/待核验/);assert.equal(p.novelty,'有先行工作 [Q1]');});
