import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import * as Catalog from '../../../chrome/content/zotero/research/shared/material-catalog.mjs';
import * as C from '../../../chrome/content/zotero/research/shared/writing-completion.mjs';
import * as M from '../../../chrome/content/zotero/research/shared/manuscript-model.mjs';
const code=await readFile(new URL('../../../chrome/content/zotero/xpcom/research/manuscript-automation.js',import.meta.url),'utf8');
function setup(responses){const material=M.material({id:'outside-project',kind:'paragraph',title:'方法来源',sourceText:'The method uses real samples.',anchor:{attachmentID:3,pageIndex:2}}),p=M.createProject('研究'),b=M.block('paragraph',p.sections[0].id);p.blocks.push(b);const inputs=[],E={manuscripts:{model:M,assetLibrary:()=>({[material.id]:material}),check:()=>[]},studio:{request:async(_,input)=>{inputs.push(input);return {value:responses.length>1?responses.shift():responses[0],model:'fixture'};}},assets:{key:()=> 'hash'},searchAcademic:async()=>[{title:'Online paper',abstract:'The study reports a limitation.',url:'https://arxiv.org/abs/example'}]};vm.runInNewContext(code,{Zotero:{Research:E},URL,ChromeUtils:{importESModule:path=>path.includes('material-catalog')?Catalog:C}});return {E,p,b,material,inputs};}
test('coauthor can search/read shared materials but does not mutate draft before acceptance',async()=>{const {E,p,b,material}=setup([{calls:[{name:'search_materials',arguments:{query:'method'}}]},{calls:[{name:'read_material',arguments:{id:'outside-project'}}]},{text:'方法使用真实样本。',evidence:[{materialID:'outside-project',quote:'The method uses real samples.'}]}]);const out=await E.manuscripts.coauthor(p,b.id,'说明方法',()=>{});assert.equal(out.materials[0].id,material.id);assert.equal(p.materials.length,0);assert.equal(b.text,'');assert.equal(out.trace.length,2);});
test('coauthor rejects fabricated function calls and numbers',async()=>{let x=setup([{calls:[{name:'eval',arguments:{code:'deleteAll()'}}]}]);await assert.rejects(x.E.manuscripts.coauthor(x.p,x.b.id,'写作',()=>{}),/未开放/);x=setup([{calls:[{name:'read_material',arguments:{id:'outside-project'}}]},{text:'结果提高 99%。',evidence:[{materialID:'outside-project',quote:'The method uses real samples.'}]}]);await assert.rejects(x.E.manuscripts.coauthor(x.p,x.b.id,'写作',()=>{}),/数字/);});
test('tool search results alone cannot be used as read evidence',async()=>{const x=setup([{calls:[{name:'search_materials',arguments:{query:'method'}}]},{text:'方法使用真实样本。',evidence:[{materialID:'outside-project',quote:'The method uses real samples.'}]}]);await assert.rejects(x.E.manuscripts.coauthor(x.p,x.b.id,'写作',()=>{}),/未知/);});
test('web sources preserve abstract-only coverage and URL',async()=>{const x=setup([{calls:[{name:'search_papers',arguments:{query:'method'}}]},{text:'摘要提到一项局限。',evidence:[{materialID:'web-hash',quote:'The study reports a limitation.'}]}]);const out=await x.E.manuscripts.coauthor(x.p,x.b.id,'写作',()=>{});assert.match(out.materials[0].coverage,/仅依据摘要/);assert.match(out.materials[0].anchor.url,/arxiv/);});
test('cancelled coauthor cannot produce a suggestion',async()=>{const x=setup([]);await assert.rejects(x.E.manuscripts.coauthor(x.p,x.b.id,'写作',()=>{},{aborted:true}),/取消/);});
