import test from 'node:test';
import assert from 'node:assert/strict';
import * as M from '../../../chrome/content/zotero/research/shared/manuscript-model.mjs';
import {topicCards} from '../../../chrome/content/zotero/research/shared/topic-materials.mjs';
import {protectEdit,safeNumbers} from '../../../chrome/content/zotero/research/shared/writing-protection.mjs';
test('topic evidence requires exact source; ideas never become evidence',()=>{const m=M.material({kind:'abstract',sourceText:'The accuracy is 95%.',anchor:{paperItemID:4},coverage:'仅依据摘要'});const card={kind:'evidence',title:'结果',summary:'准确率为 95%。',sourceID:m.id,quote:'The accuracy is 95%.'};const [valid]=topicCards({cards:[card]},[m],'主题');assert.equal(valid.paperItemID,4);assert.equal(valid.coverage,'仅依据摘要');assert.equal(valid.verification,'unverified');assert.throws(()=>topicCards({cards:[{...card,quote:'invented'}]},[m],''));assert.throws(()=>topicCards({cards:[{...card,summary:'准确率为 5%'}]},[m],''));const [idea]=topicCards({cards:[{kind:'idea',title:'假设',summary:'是否可以迁移？'}]},[],'');const p=M.createProject('研究'),b=M.block('paragraph',p.sections[0].id,{materials:[{id:idea.id}]});p.materials.push(idea);assert.throws(()=>M.validateProposal(p,b,{text:'结果成立',evidence:[{materialID:idea.id,quote:'是否'}]}));});
test('AI preserves math delimiters, nested environments, citations and unknown macros',()=>{for(const token of [String.raw`$x^2$`,String.raw`\(x+1\)`,String.raw`\[x+1\]`,String.raw`\cite{paper-id}`,String.raw`\custom[opt]{a{b}}`,String.raw`\begin{align}x&=1\end{align}`]){protectEdit('原文 '+token,'润色 '+token);assert.throws(()=>protectEdit(token,token.replace(/x|paper|custom|a/, 'changed')));}assert.throws(()=>protectEdit(String.raw`\(x`,''));assert.throws(()=>safeNumbers('95%','5%'));});
test('accepted selection diff preserves surrounding runs and rejects locked or stale changes',()=>{const p=M.createProject('研究'),b=M.block('paragraph',p.sections[0].id,{text:'前文修改后文',runs:[{text:'前文',bold:true},{text:'修改'},{text:'后文',italic:true}]});p.blocks.push(b);const d={status:'pending',blockID:b.id,before:b.text,after:'前文润色后文',selection:{start:2,end:4},evidence:[],materialRevisions:[],preserveClaim:true,originalClaim:false};b.locked=true;assert.throws(()=>M.applyProposal(p,d));b.locked=false;M.applyProposal(p,d);assert.deepEqual(b.runs,[{text:'前文',bold:true},{text:'润色'},{text:'后文',italic:true}]);assert.equal(b.claim,false);assert.throws(()=>M.applyProposal(p,d));});

test('polish preserves physical units',()=>{assert.throws(()=>safeNumbers('延迟 10 ms','延迟 10 s'));safeNumbers('延迟 10 ms','延迟10ms');});

test('spaced LaTeX command arguments remain protected',()=>{assert.throws(()=>protectEdit(String.raw`\cite {stable-id}`,String.raw`\cite {other-id}`));assert.throws(()=>protectEdit(String.raw`\custom [option] {content}`,String.raw`\custom [option] {changed}`));});
