describe('Manuscript assembly native frontend',function(){
 let win,R=Zotero.Research,ui,frame,projectID,output,folder,paper,attachment;
 const wait=async fn=>{for(let i=0;i<1200;i++){if(fn())return;await Zotero.Promise.delay(40);}throw Error('UI timeout: '+(ui?.$('status')?.textContent||''));};
 const click=(host,text)=>{const b=[...host.querySelectorAll('button')].find(b=>b.textContent===text);assert.exists(b,text);b.click();};
 const edit=(input,text,event='input')=>{if(input.isContentEditable)input.textContent=text;else input.value=text;input.dispatchEvent(new frame.contentWindow.Event(event,{bubbles:true}));};
 async function capture(name){await Zotero.Promise.delay(150);const image=await win.browsingContext.currentWindowGlobal.drawSnapshot(null,1,'white'),canvas=win.document.createElementNS('http://www.w3.org/1999/xhtml','canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));await IOUtils.write(PathUtils.join(folder,name),new Uint8Array(await blob.arrayBuffer()));image.close();}
 before(async()=>{win=await loadZoteroPane();win.Zotero_Tabs.closeAll();win.focus();win.resizeTo(1550,980);await R.attachWindow(win);folder=PathUtils.join(Zotero.DataDirectory.dir,'manuscript-acceptance');await IOUtils.makeDirectory(folder,{ignoreExisting:true});});
 after(()=>win?.close());
 it('restores persisted assembly and conversation after an application restart',async function(){
  const path=PathUtils.join(folder,'result.json');if(!await IOUtils.exists(path))this.skip();const previous=JSON.parse(await IOUtils.readUTF8(path)),saved=R.manuscripts.get(previous.projectID);if(!saved)this.skip();
  await R.manuscripts.open(previous.projectID);await wait(()=>{const f=win.document.getElementById('manuscript-'+previous.projectID);return f?.contentWindow.ManuscriptUI?.ready;});const f=win.document.getElementById('manuscript-'+previous.projectID),restored=f.contentWindow.ManuscriptUI;assert.equal(restored.p.blocks.length,saved.blocks.length);assert.deepEqual(JSON.parse(JSON.stringify(restored.p.chat)),saved.chat);assert.equal(restored.p.ui.blockID,saved.ui.blockID);assert.equal(restored.p.materials.length,saved.materials.length);assert.equal(restored.p.ui.aiOpen,saved.ui.aiOpen);assert.equal(restored.p.ui.leftOpen,saved.ui.leftOpen);assert.equal(restored.p.ui.rightOpen,saved.ui.rightOpen);win.Zotero_Tabs.close(f.parentElement.id);
 });
 it('creates a project from writing home and opens a native central tab',async function(){
  const home=await R.openWorkflow('writing');assert.isTrue(home.$('legacy-writing').hidden);home.$('new-manuscript').click();home.$('manuscript-name').value='论文装配前台验收 · 实验报告';home.$('manuscript-name').closest('form').dispatchEvent(new (home.$('manuscript-name').ownerDocument.defaultView.Event)('submit',{bubbles:true,cancelable:true}));
  await wait(()=>{frame=win.document.querySelector('iframe[id^="manuscript-"]');ui=frame?.contentWindow.ManuscriptUI;return ui?.ready;});projectID=ui.p.id;assert.equal(win.Zotero_Tabs.selectedType,'manuscript');assert.lengthOf(ui.$('insert-tools').children,5);assert.isTrue(ui.$('ai').hidden);await capture('01-project-and-tab.png');
 });
 it('inserts a table using the grid, binds CSV data and edits cells in the native page',async function(){
  click(ui.$('insert-tools'),'表格');assert.exists(ui.$('grid'));await capture('02-table-grid.png');ui.$('grid').querySelector('[data-row="3"][data-col="3"]').click();await wait(()=>ui.p.blocks.some(b=>b.type==='table'));let table=ui.p.blocks.find(b=>b.type==='table');assert.equal(table.table.rows.length,3);
  const csv=PathUtils.join(folder,'experiment.csv');await IOUtils.writeUTF8(csv,'模型,准确率,样本量\n基线,91.2%,100\n改进方法,93.4%,100\n');const pick=sinon.stub(R,'pick').resolves(csv);try{const bind=ui.$('details').querySelector('details');bind.open=true;click(ui.$('details'),'从文件选择数据');await wait(()=>table.table.binding);}finally{pick.restore();}
  assert.equal(table.table.rows[2][1].text,'93.4%');const caption=[...ui.$('details').querySelectorAll('label')].find(n=>n.textContent.startsWith('表题')).querySelector('input');edit(caption,'受控验收数据（非论文实验结果）','change');
  const cell=ui.$('canvas').querySelector('[data-row="1"][data-col="0"] .cell-editor');cell.click();edit(cell,'基线模型');await ui.persist();await capture('03-bound-table.png');
  assert.equal(table.table.rows[1][0].text,'基线模型');assert.equal(R.manuscripts.get(projectID).blocks[0].table.rows[1][0].text,'基线模型');
 });
 it('assembles an evidence-linked paragraph, reviews AI diff and restores editor state',async function(){
  click(ui.$('details'),'在表后添加分析段落');await wait(()=>ui.p.blocks.some(b=>b.type==='paragraph'));let b=ui.p.blocks.find(b=>b.type==='paragraph');const input=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);edit(input,'以下数据仅用于软件验收：改进方法准确率为 93.4%，基线为 91.2%，样本量均为 100。不能把本表当作真实论文的实验结论。');
  click(ui.$('left-tabs'),'◇ 证据网络');assert.exists(ui.$('library').querySelector('[data-evidence]'));await capture('04-evidence-network.png');
  ui.$('toggle-ai').click();const m=ui.p.materials[0],mock=sinon.stub(R.studio,'request').resolves({value:{text:'验收数据中，改进方法准确率为 93.4%。此处只检验导出与证据回链，不能推断论文结论。',evidence:[{materialID:m.id,quote:'93.4%',cell:{row:2,col:1}}]},model:'controlled-ui-fixture'});
  try{ui.$('ai-prompt').value='请保留验收边界并简化当前段落';ui.$('ai-form').dispatchEvent(new frame.contentWindow.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>ui.p.proposals.length);assert.include(b.text,'样本量均为 100');await capture('05-reviewed-diff.png');click(ui.$('diff'),'确认应用到当前模块');assert.notInclude(b.text,'样本量均为 100');}finally{mock.restore();}
  ui.$('toggle-ai').click();ui.$('toggle-right').click();await ui.persist();await R.store.flush();const section=ui.p.ui.sectionID,block=b.id;win.Zotero_Tabs.close(frame.parentElement.id);await Zotero.Promise.delay(200);await R.manuscripts.open(projectID);await wait(()=>{frame=win.document.getElementById('manuscript-'+projectID);ui=frame?.contentWindow.ManuscriptUI;return ui?.ready;});assert.equal(ui.p.ui.sectionID,section);assert.equal(ui.p.ui.blockID,block);assert.isTrue(ui.$('right').hidden);assert.isAtLeast(ui.p.chat.length,2);ui.$('toggle-right').click();
 });
 it('imports real Zotero note and annotation objects and drags their source into a module',async function(){
  const pdf=Zotero.Prefs.get('extensions.easysch.testPDF',true);if(!pdf)this.skip();
  paper=await createDataObject('item',{itemType:'journalArticle',title:'C-AMC: Towards Complete Automatic Modulation Classification',date:'2025'});
  attachment=await Zotero.Attachments.importFromFile({file:Zotero.File.pathToFile(pdf),parentItemID:paper.id});
  const note=new Zotero.Item('note');note.libraryID=paper.libraryID;note.parentID=paper.id;note.setNote('<p>我的阅读记录：先核对任务定义，再对照自己的实验。这是一条验收用个人笔记。</p>');await note.saveTx();
  const annotation=new Zotero.Item('annotation');annotation.libraryID=paper.libraryID;annotation.parentID=attachment.id;annotation.annotationType='highlight';annotation.annotationText='C-AMC';annotation.annotationComment='验收用批注：回到标题所在页核对来源';annotation.annotationColor='#ffd400';annotation.annotationSortIndex='00000|000000|00000';annotation.annotationPageLabel='1';annotation.annotationPosition=JSON.stringify({pageIndex:0,rects:[[90,878.6,167.83,912.6]]});await annotation.saveTx();
  note.setNote('<p>我的阅读记录</p><span data-annotation="'+encodeURIComponent(JSON.stringify({attachmentURI:Zotero.URI.getItemURI(attachment),annotationKey:annotation.key,position:JSON.parse(annotation.annotationPosition)}))+'">C-AMC</span>');await note.saveTx();
  win.Zotero_Tabs.select('zotero-pane');await win.ZoteroPane.selectItem(paper.id);win.Zotero_Tabs.select(frame.parentElement.id);
  click(ui.$('left-tabs'),'▧ 素材库');click(ui.$('library'),'＋ 从笔记、批注或实验选素材');await wait(()=>ui.$('popover-content').querySelector(`[data-paper="${paper.id}"]`));ui.$('popover-content').querySelector(`[data-paper="${paper.id}"]`).click();await wait(()=>ui.$('popover-content').querySelector(`[data-source-item="${annotation.id}"]`));for(const checkbox of ui.$('popover-content').querySelectorAll('[data-source-item]'))if(checkbox.dataset.sourceItem)checkbox.click();await wait(()=>![...ui.$('popover-content').querySelectorAll('[data-source-item]')].some(n=>n.disabled));click(ui.$('popover-content'),'完成选择，开始装配');
  const m=ui.p.materials.find(m=>m.kind==='annotation');assert.exists(m,JSON.stringify({materials:ui.p.materials.map(m=>({kind:m.kind,title:m.title})),popup:ui.$('popover-content').textContent,selected:win.ZoteroPane.getSelectedItems().map(x=>x.id)}));assert.equal(m.attachmentID,attachment.id);assert.equal(m.pageIndex,0);assert.equal(m.position.rects[0][0],90);assert.equal(m.sourceText,'C-AMC');assert.isTrue(ui.p.materials.some(m=>m.kind==='note'));
  const card=ui.$('library').querySelector(`[data-material="${m.id}"]`),data=new frame.contentWindow.DataTransfer();card.dispatchEvent(new frame.contentWindow.DragEvent('dragstart',{bubbles:true,dataTransfer:data}));const target=ui.$('canvas').querySelector('.paper');target.dispatchEvent(new frame.contentWindow.DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));await wait(()=>ui.p.blocks.some(b=>b.materials.some(x=>x.id===m.id)));
  const b=ui.p.blocks.find(b=>b.materials.some(x=>x.id===m.id));ui.selectBlock(b.id);edit(ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`),'阅读安排：标题批注仅提供定位，研究结论仍需核对正文和实验。');click(ui.$('left-tabs'),'◇ 证据网络');await capture('07-note-annotation-source.png');
  const source=ui.$('library').querySelector(`[data-evidence="${b.id}"] button`);source.click();await wait(()=>Zotero.Reader._readers.find(r=>r.itemID===attachment.id));assert.equal(win.Zotero_Tabs.selectedType,'reader');win.Zotero_Tabs.select(frame.parentElement.id);
 });
 it('uses readable day/night dialogs and builds reviewed source-linked topic assets',async function(){
  const w=frame.contentWindow;
  click(ui.$('left-tabs'),'▧ 素材库');click(ui.$('library'),'建立主题素材库');
  assert.notInclude(ui.$('topic-prompt').value,'MouseEvent');
  for(const mode of ['light','dark']){w.ResearchAppearance.set(mode);const style=w.getComputedStyle(ui.$('build-topic')),dialog=w.getComputedStyle(ui.$('popover'));assert.notEqual(style.color,style.backgroundColor);assert.notEqual(dialog.color,dialog.backgroundColor);assert.equal(w.document.documentElement.dataset.appearance,mode);const active=w.getComputedStyle(ui.$('steps').querySelector('.active'));const luminance=c=>{const v=c.match(/[0-9.]+/g).slice(0,3).map(n=>{n=+n/255;return n<=0.04045?n/12.92:((n+0.055)/1.055)**2.4;});return .2126*v[0]+.7152*v[1]+.0722*v[2];};for(const x of [style,dialog,active]){const a=luminance(x.color),b=luminance(x.backgroundColor);assert.isAtLeast((Math.max(a,b)+.05)/(Math.min(a,b)+.05),4.5,mode+' text contrast');}await capture('08-topic-'+mode+'.png');}
  w.ResearchAppearance.set('light');
  const request=sinon.stub(R.studio,'request').callsFake(async(system,input)=>{const source=input.sources.find(x=>x.text.includes('C-AMC'));assert.exists(source,'retrieved real library source');return {value:{cards:[{kind:'evidence',title:'主题定位素材',category:'研究背景',summary:'标题提供研究任务线索，结论仍需阅读正文。',sourceID:source.id,quote:'C-AMC'},{kind:'idea',title:'待验证的实验方向',summary:'比较不同采样条件下的方法表现，需要设计实验验证。'}]},model:'controlled-ui-fixture'};});
  let assetID;
  try{edit(ui.$('topic-prompt'),'C-AMC 调制识别');ui.$('build-topic').click();await wait(()=>ui.$('topic-results').querySelectorAll('.theme-card').length===2);assert.include(ui.$('topic-results').textContent,'待验证');await capture('09-reviewed-topic-cards.png');click(ui.$('topic-results'),'确认加入主题素材库');await wait(()=>!ui.$('popover').open);const m=ui.p.materials.find(m=>m.title==='主题定位素材');assert.exists(m.assetID);assetID=m.assetID;assert.equal(m.sourceText,'C-AMC');assert.equal(m.verification,'unverified');
   click(ui.$('library'),'建立主题素材库');edit(ui.$('topic-prompt'),'C-AMC 调制识别');ui.$('build-topic').click();await wait(()=>ui.$('topic-results').querySelectorAll('.theme-card').length===2);click(ui.$('topic-results'),'确认加入主题素材库');await wait(()=>!ui.$('popover').open);assert.equal(ui.p.materials.filter(m=>m.assetID===assetID).length,1);
  }finally{request.restore();}
  const m=ui.p.materials.find(m=>m.assetID===assetID),card=ui.$('library').querySelector(`[data-material="${m.id}"]`),data=new w.DataTransfer();card.dispatchEvent(new w.DragEvent('dragstart',{bubbles:true,dataTransfer:data}));ui.$('canvas').querySelector('.paper').dispatchEvent(new w.DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));await wait(()=>ui.p.blocks.some(b=>b.materials.some(x=>x.id===assetID)));const b=ui.p.blocks.find(b=>b.materials.some(x=>x.id===assetID));ui.selectBlock(b.id);edit(ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`),'素材仅提供研究主题线索，仍须核对论文方法与实验。');await ui.persist();
  const copy=await R.manuscripts.copy(projectID);assert.equal(R.manuscripts.get(copy.id).materials.find(m=>m.assetID===assetID).id,assetID);await R.manuscripts.remove(copy.id);
 });
 it('reviews paragraph edits and respects outline, text, table and IME keyboard focus',async function(){
  const w=frame.contentWindow,key=(n,k,mods={})=>{n.focus();const e=new w.KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true,...mods});n.dispatchEvent(e);return e;};
  const b=ui.p.blocks.find(b=>b.type==='paragraph'&&b.materials.some(x=>ui.p.materials.find(m=>m.id===x.id)?.title==='主题定位素材'));ui.selectBlock(b.id);const original=b.text,model=sinon.stub(R.studio,'request').resolves({value:{text:'这一素材提供主题线索；方法与实验仍须回到论文核对。',evidence:[]},model:'controlled-ui-fixture'});
  try{click(ui.$('details'),'润色');await wait(()=>!ui.busy);assert.isTrue(ui.p.proposals.some(d=>d.purpose==='polish'),ui.$('status').textContent);assert.equal(b.text,original);await capture('10-paragraph-diff.png');click(ui.$('diff'),'确认应用到当前模块');assert.notEqual(b.text,original);key(ui.$('canvas'),'z',{ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,original);}finally{model.restore();}
  click(ui.$('left-tabs'),'☷ 论文结构');let outline=ui.$('library').querySelector(`[data-outline-block="${b.id}"]`);outline.click();const count=ui.p.blocks.length,materials=ui.p.materials.length;key(outline,'Delete',{isComposing:true});assert.equal(ui.p.blocks.length,count);key(outline,'Delete');assert.equal(ui.p.blocks.length,count-1);assert.equal(ui.p.materials.length,materials);key(ui.$('canvas'),'z',{ctrlKey:true});assert.equal(ui.p.blocks.length,count);assert.isTrue(!!Zotero.Items.get(paper.id));await capture('11-outline-undo.png');
  const input=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);assert.isFalse(key(input,'Delete').defaultPrevented);assert.isFalse(key(ui.$('ai-prompt'),'z',{ctrlKey:true}).defaultPrevented);assert.isFalse(key(ui.$('ai-prompt'),'Delete').defaultPrevented);
  input.dispatchEvent(new w.InputEvent('beforeinput',{bubbles:true,inputType:'insertText',data:'补充'}));edit(input,original+'补充');key(input,'z',{ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,original);assert.isTrue(!!w.document.activeElement.closest('.editable'),'undo keeps writing focus');
  const table=ui.p.blocks.find(b=>b.type==='table');ui.selectBlock(table.id);const cells=table.table.rows.map(r=>r.map(c=>c.text));ui.selectedCells=[{r:1,c:0},{r:1,c:1}];const cell=ui.$('canvas').querySelector(`[data-id="${table.id}"] .cell-editor`);key(cell,'Delete');assert.equal(ui.p.blocks.find(x=>x.id===table.id).table.rows[1][0].text,'');key(ui.$('canvas'),'z',{ctrlKey:true});assert.deepEqual(ui.p.blocks.find(x=>x.id===table.id).table.rows.map(r=>r.map(c=>c.text)),cells);ui.selectedCells=[];await ui.persist();
 });
 it('applies selected-text diffs and supports outline rename, move, multiselect and redo',async function(){
  const w=frame.contentWindow,key=(n,k,mods={})=>{n.focus();n.dispatchEvent(new w.KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true,...mods}));},b=ui.p.blocks.find(b=>b.type==='paragraph'&&b.materials.some(x=>ui.p.materials.find(m=>m.id===x.id)?.title==='主题定位素材'));
  ui.selectBlock(b.id);const node=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`),before=b.text;node.focus();const range=w.document.createRange(),textNode=w.document.createTreeWalker(node,w.NodeFilter.SHOW_TEXT).nextNode();range.setStart(textNode,0);range.setEnd(textNode,2);w.getSelection().removeAllRanges();w.getSelection().addRange(range);node.dispatchEvent(new w.MouseEvent('mouseup',{bubbles:true}));assert.exists(ui.$('selection-tools'));
  const fake=sinon.stub(R.studio,'request').resolves({value:{text:'这份素材',evidence:[]},model:'controlled-selection-fixture'});try{click(ui.$('selection-tools'),'润色选中文字');await wait(()=>!ui.busy);click(ui.$('diff'),'确认应用到当前模块');assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,'这份素材'+before.slice(2));key(ui.$('canvas'),'z',{ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,before);key(ui.$('canvas'),'y',{ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,'这份素材'+before.slice(2));key(ui.$('canvas'),'z',{ctrlKey:true});}finally{fake.restore();}
  click(ui.$('left-tabs'),'☷ 论文结构');let outline=ui.$('library').querySelector(`[data-outline-block="${b.id}"]`);outline.click();key(outline,'F2');assert.isTrue(ui.$('popover').open);edit(ui.$('popover-content').querySelector('input'),'研究主题说明');click(ui.$('popover-content'),'保存名称');assert.equal(ui.p.blocks.find(x=>x.id===b.id).title,'研究主题说明');key(ui.$('canvas'),'z',{ctrlKey:true});
  outline=ui.$('library').querySelector(`[data-outline-block="${b.id}"]`);outline.click();const order=ui.p.blocks.map(b=>b.id);key(outline,'ArrowUp',{altKey:true});assert.notDeepEqual(ui.p.blocks.map(b=>b.id),order);key(ui.$('canvas'),'z',{ctrlKey:true});assert.deepEqual(ui.p.blocks.map(b=>b.id),order);
  const buttons=[...ui.$('library').querySelectorAll('[data-outline-block]')],n=ui.p.blocks.length;buttons[0].click();buttons[1].dispatchEvent(new w.MouseEvent('click',{bubbles:true,ctrlKey:true}));assert.equal(ui.p.ui.selectedBlocks.length,2);key(buttons[1],'c',{ctrlKey:true});key(ui.$('canvas'),'v',{ctrlKey:true});assert.equal(ui.p.blocks.length,n+2);key(ui.$('canvas'),'z',{ctrlKey:true});assert.equal(ui.p.blocks.length,n);
  const section=ui.$('library').querySelector('.section-card'),materialCount=ui.p.materials.length,sectionCount=ui.p.sections.length;section.click();key(ui.$('library').querySelector(`[data-section="${section.dataset.section}"]`),'Delete');assert.include(ui.$('popover-content').textContent,'子模块');click(ui.$('popover-content'),'移除章节及子模块');assert.equal(ui.p.sections.length,sectionCount-1);assert.equal(ui.p.materials.length,materialCount);key(ui.$('canvas'),'z',{ctrlKey:true});assert.equal(ui.p.sections.length,sectionCount);await ui.persist();
 });
 it('completes material cards with Ctrl+Tab, reviews tools, and keeps outline context actions undoable',async function(){
  const w=frame.contentWindow,b=ui.p.blocks.find(b=>b.type==='paragraph'&&b.materials.length),before=b.text;
  ui.selectBlock(b.id);ui.renderEditor();const card=ui.$('canvas').querySelector(`[data-assembly="${b.id}"]`);assert.exists(card);const goal=card.querySelector('.assembly-goal');edit(goal,'解释素材可以支持什么，以及无法支持什么');goal.focus();
  const m=ui.p.materials.find(m=>m.id===b.materials[0].id);let calls=0;
  const fake=sinon.stub(R.studio,'request').callsFake(async(system,input)=>{if(!input.tools)return {value:{field:'通信',method:'调制识别'},model:'controlled-tags'};calls++;if(calls===1)return {value:{calls:[{name:'chapter_context',arguments:{}}]},model:'controlled-tools'};return {value:{text:'这些材料提供来源定位，仍需结合实验条件解释适用范围。',evidence:[{materialID:m.id,quote:m.sourceText.slice(0,40)}]},model:'controlled-tools'};});
  try{
   goal.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Tab',ctrlKey:true,bubbles:true,cancelable:true}));await wait(()=>!ui.busy);assert.equal(calls,2);assert.equal(win.Zotero_Tabs.selectedType,'manuscript');assert.include(ui.$('diff').textContent,'chapter_context');assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,before);await capture('12-card-completion-diff.png');click(ui.$('diff'),'确认应用到当前模块');assert.notEqual(ui.p.blocks.find(x=>x.id===b.id).text,before);ui.$('canvas').dispatchEvent(new w.KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true}));assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,before);
  }finally{fake.restore();}
  const box=ui.$('canvas').querySelector(`[data-assembly="${b.id}"]`);box.dispatchEvent(new w.PointerEvent('pointerenter'));assert.isTrue(ui.$('canvas').classList.contains('reveal-materials'));box.dispatchEvent(new w.PointerEvent('pointerleave'));assert.isFalse(ui.$('canvas').classList.contains('reveal-materials'));
  click(ui.$('left-tabs'),'◇ 证据网络');const chains=[...ui.$('library').querySelectorAll('[data-evidence]')];assert.isAtLeast(chains.length,2);const data=new w.DataTransfer();chains[0].querySelector('.evidence-grip').dispatchEvent(new w.DragEvent('dragstart',{bubbles:true,dataTransfer:data}));chains[1].dispatchEvent(new w.DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));assert.equal(ui.p.ui.evidenceOrder[1],chains[0].dataset.evidence);await capture('13-sortable-evidence.png');
  click(ui.$('left-tabs'),'☷ 论文结构');const outline=ui.$('library').querySelector(`[data-outline-block="${b.id}"]`);outline.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:180,clientY:230}));assert.exists(w.document.getElementById('assembly-context'));await capture('14-outline-context.png');click(w.document.getElementById('assembly-context'),'删除模块 · Delete');assert.isFalse(ui.p.blocks.some(x=>x.id===b.id));ui.$('canvas').dispatchEvent(new w.KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true}));assert.isTrue(ui.p.blocks.some(x=>x.id===b.id));
 });
 it('automatically indexes an imported PDF into persistent paragraph sources',async function(){
  if(!attachment)this.skip();await wait(()=>R.manuscripts.indexState()[attachment.id]?.count>0);const sources=Object.values(R.manuscripts.assetLibrary()).filter(m=>m.attachmentID===attachment.id&&m.kind==='paragraph');assert.isAbove(sources.length,10);assert.isTrue(sources.every(m=>m.position?.rects?.length&&Number.isInteger(m.pageIndex)&&m.sourceText));
  const count=sources.length;await R.manuscripts.indexArticle(attachment.id);assert.isTrue(R.manuscripts.indexState()[attachment.id].cacheHit);assert.equal(Object.values(R.manuscripts.assetLibrary()).filter(m=>m.attachmentID===attachment.id&&m.kind==='paragraph').length,count);
  click(ui.$('left-tabs'),'▧ 素材库');const search=ui.$('library').querySelector('input');edit(search,'C-AMC');assert.include(ui.$('library').textContent,'段');await capture('15-imported-paragraph-assets.png');
 });
 it('exports from the visible button with editable OMML and preserved table XML',async function(){
  for(const b of ui.p.blocks){ui.selectBlock(b.id);click(ui.$('details'),'核验来源');await wait(()=>ui.$('popover').open);click(ui.$('popover-content'),'来源支持当前内容，标记已核验');}
  click(ui.$('insert-tools'),'公式');await wait(()=>ui.p.blocks.some(b=>b.type==='formula'));const formula=ui.$('details').querySelector('textarea');edit(formula,'E=mc^2','change');
  if(paper){click(ui.$('insert-tools'),'引用');await wait(()=>[...ui.$('popover-content').querySelectorAll('button')].some(b=>b.textContent===paper.getField('title')));click(ui.$('popover-content'),paper.getField('title'));await wait(()=>ui.p.blocks.some(b=>b.type==='citation'));}
  const pic=sinon.stub(R,'pick').resolves(PathUtils.join(folder,'03-bound-table.png'));try{click(ui.$('insert-tools'),'图片');await wait(()=>ui.p.blocks.some(b=>b.type==='image'));}finally{pic.restore();}
  const pick=sinon.stub(R,'pick').resolves(folder);try{ui.$('export').click();await wait(()=>ui.lastExport||!ui.busy&&ui.$('status').classList.contains('error'));assert.exists(ui.lastExport,ui.$('status').textContent);output=ui.lastExport.path;}finally{pick.restore();}
  assert.isTrue(await IOUtils.exists(output));let zip=Cc['@mozilla.org/libjar/zip-reader;1'].createInstance(Ci.nsIZipReader);zip.open(Zotero.File.pathToFile(output));try{const stream=zip.getInputStream('word/document.xml');const xml=await Zotero.File.getContentsAsync(stream);stream.close();assert.include(xml,'m:oMath');assert.include(xml,'w:tbl');assert.include(xml,'w:tcBorders');assert.include(xml,'w:vAlign');assert.include(xml,'受控验收数据');assert.isTrue(zip.hasEntry('word/header1.xml'));}finally{zip.close();}
  await IOUtils.writeUTF8(PathUtils.join(folder,'result.json'),JSON.stringify({projectID,output,screenshots:folder},null,2));await capture('06-exported.png');
  ui.lastExport=null;ui.$('preview').click();await wait(()=>ui.lastExport||!ui.busy&&ui.$('status').classList.contains('error'));assert.exists(ui.lastExport,ui.$('status').textContent);
 });
});
