describe('Material catalog in native Zotero',function(){
 this.timeout(90000);let win,ui,frame,R=Zotero.Research,project,material,folder;const report={type:'真实 Zotero 前台事件，使用已有真实论文素材；输入法为受控事件',checks:[]};
 const wait=async (fn,attempts=160)=>{for(let i=0;i<attempts;i++){if(await fn())return;await Zotero.Promise.delay(100);}throw Error('等待界面超时 '+ui?.$('status').textContent);};
 const click=(host,text)=>{const b=[...host.querySelectorAll('button')].find(n=>n.textContent===text);assert.exists(b,text);b.click();};
 const ev=(node,name,options={})=>node.dispatchEvent(new frame.contentWindow[name==='keydown'?'KeyboardEvent':name.startsWith('composition')?'CompositionEvent':'Event'](name,{bubbles:true,cancelable:true,...options}));
 async function shot(name){const img=await win.browsingContext.currentWindowGlobal.drawSnapshot(null,1,'white'),canvas=win.document.createElementNS('http://www.w3.org/1999/xhtml','canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);const blob=await new Promise(r=>canvas.toBlob(r));await IOUtils.write(PathUtils.join(folder,name),new Uint8Array(await blob.arrayBuffer()));img.close();}
 before(async()=>{win=await loadZoteroPane();win.Zotero_Tabs.closeAll();win.focus();await Zotero.Promise.delay(6500);win.resizeTo(1500,1000);await R.attachWindow(win);folder=PathUtils.join(Zotero.DataDirectory.dir,'catalog-acceptance');await IOUtils.makeDirectory(folder,{ignoreExisting:true});material=Object.values(R.manuscripts.assetLibrary()).find(m=>m.kind==='semantic'&&m.sourceVersion==='bdfaa68d8984f0dc02beaca527b76f207d99b666d31d1da728ee0728182df697'&&/[\u3400-\u9fff]/.test(m.summary)&&m.attachmentID);assert.exists(material,'需要已有真实论文中文素材');project=Object.values(R.manuscripts.all()).find(p=>p.title==='素材整理验收')||await R.manuscripts.create('素材整理验收');await R.manuscripts.open(project.id);await wait(()=>{frame=win.document.getElementById('manuscript-'+project.id);ui=frame?.contentWindow.ManuscriptUI;return ui?.ready;});});
 after(async()=>{report.projectID=project?.id;await IOUtils.writeUTF8(PathUtils.join(folder,'report.json'),JSON.stringify(report,null,2));win?.close();});
 it('reuses PDF and project tabs, and searches without replacing the composing input',async()=>{
  for(let n=0;n<3;n++)await Zotero.Reader.open(material.attachmentID);assert.equal(Zotero.Reader._readers.filter(r=>r.itemID===material.attachmentID&&!r._isTabClosed).length,1);for(let n=0;n<3;n++)await R.manuscripts.open(project.id);assert.equal(win.document.querySelectorAll('#manuscript-'+project.id).length,1);
  const input=ui.$('material-search');assert.exists(input);input.focus();ev(input,'compositionstart');input.value=(material.title.match(/[\u3400-\u9fff]{2,}/)||[material.title])[0].slice(0,5);ev(input,'input');await Zotero.Promise.delay(250);assert.equal(ui.$('material-search'),input);ev(input,'compositionend');await Zotero.Promise.delay(500);assert.equal(ui.$('material-search'),input);assert.exists(ui.$('material-results').querySelector(`[data-material="${material.id}"]`));assert.include(ui.$('material-results').textContent,'命中');await shot('01-chinese-search.png');report.checks.push('同一附件三次打开一个标签；项目复用；中文组词事件不重建输入框');
 });
 it('changes type through context menu, removes only topic membership and restores undo',async()=>{
  const card=ui.$('material-results').querySelector(`[data-material="${material.id}"]`);card.dispatchEvent(new frame.contentWindow.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:100,clientY:350}));click(frame.contentDocument.getElementById('material-context'),'修改类型');click(ui.$('popover-content'),'方法');await ui.persist();assert.equal(ui.p.materialCatalog.entries[material.id].type,'方法');
  const count=Object.keys(R.manuscripts.assetLibrary()).length;const next=ui.$('material-results').querySelector(`[data-material="${material.id}"]`);next.click();next.focus();ev(next,'keydown',{key:'Delete'});assert.isFalse(ui.p.materialCatalog.entries[material.id].topics.includes(ui.p.id));assert.equal(Object.keys(R.manuscripts.assetLibrary()).length,count);ev(ui.$('canvas'),'keydown',{key:'z',ctrlKey:true});assert.isTrue(ui.p.materialCatalog.entries[material.id].topics.includes(ui.p.id));report.checks.push('右键修改类型；Delete 仅移除主题关联；Ctrl+Z 恢复且资产数不变');
  ui.materialQuery='';ui.renderLibrary();const sort=ui.$('library').querySelector('select');sort.value='manual';ev(sort,'change');const cards=[...ui.$('material-results').querySelectorAll('[data-material]')];assert.isAbove(cards.length,1);const a=cards[0],b=cards[1],id=a.dataset.material,target=b.dataset.material,data=new frame.contentWindow.DataTransfer();a.dispatchEvent(new frame.contentWindow.DragEvent('dragstart',{bubbles:true,dataTransfer:data}));b.dispatchEvent(new frame.contentWindow.DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:data,clientY:b.getBoundingClientRect().bottom-1}));b.dispatchEvent(new frame.contentWindow.DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));const key=ui.p.id+'|';assert.isAbove(ui.p.materialCatalog.orders[key].indexOf(id),ui.p.materialCatalog.orders[key].indexOf(target));await ui.persist();await R.store.flush();win.Zotero_Tabs.close(frame.parentElement.id);await R.manuscripts.open(project.id);await wait(()=>{frame=win.document.getElementById('manuscript-'+project.id);ui=frame?.contentWindow.ManuscriptUI;return ui?.ready;});assert.equal(ui.p.materialCatalog.entries[material.id].type,'方法');assert.isAbove(ui.p.materialCatalog.orders[key].indexOf(id),ui.p.materialCatalog.orders[key].indexOf(target));await shot('02-category-and-order.png');report.checks.push('拖放顺序、类型关闭重开后恢复');
 });
 it('Ctrl+Tab retrieves materials before invoking the model and can cancel without writing',async()=>{
  const block=ui.p.blocks[0];block.requirements=material.title;const node=ui.$('canvas').querySelector(`[data-id="${block.id}"] .editable`);node.focus();const stub=sinon.stub(R.manuscripts,'coauthor');try{ev(node,'keydown',{key:'Tab',ctrlKey:true});await wait(()=>ui.$('popover').open);assert.include(ui.$('popover-content').textContent,'补全前选择参考素材');assert.include(ui.$('popover-content').textContent,material.title);assert.isFalse(stub.called);await shot('03-completion-material-choice.png');ui.$('close-popover').click();await wait(()=>!ui.busy);assert.isFalse(stub.called);report.checks.push('Ctrl+Tab 先检索并展示材料选择，取消不调用模型不写正文');}finally{stub.restore();}
 });
 it('writes actual prose from the user-selected material using a real API and undoes it',async function(){
  this.timeout(180000);const b=ui.p.blocks[0],before=b.text;b.requirements='根据“'+material.title+'”的来源写一段中文解释，说明论文的论证及其适用范围。只使用本次所选素材，不扩展实验结果，不增加数字，不联网。';
  const node=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);node.focus();const real=R.studio.request,calls=[];R.studio.request=async(...args)=>{const result=await real(...args);calls.push({model:result.model,cacheHit:result.cacheHit});return result;};
  try{ev(node,'keydown',{key:'Tab',ctrlKey:true});await wait(()=>ui.$('popover').open);const label=[...ui.$('popover-content').querySelectorAll('label')].find(x=>x.textContent.includes(material.title));assert.exists(label);const checkbox=label.querySelector('input');checkbox.checked=true;ev(checkbox,'change');click(ui.$('popover-content'),'使用所选素材补全');await wait(()=>!ui.busy,1600);const after=ui.p.blocks.find(x=>x.id===b.id);assert.isAbove(after.text.length,before.length+15,ui.$('status').textContent);assert.isTrue(after.materials.some(x=>x.id===material.id));assert.isTrue(after.evidence.some(x=>x.materialID===material.id));await shot('04-real-selected-material-prose.png');report.realModel={calls,text:after.text,materialID:material.id};ev(ui.$('canvas'),'keydown',{key:'z',ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,before);report.checks.push('真实模型根据用户所选素材写入正文，保留来源，Ctrl+Z 撤销');}finally{R.studio.request=real;}
 });

});
