describe('Research theme and feasibility restoration',function(){
 this.timeout(90000);let win,frame,doc;const R=Zotero.Research,checks=[];
 const wait=async f=>{for(let i=0;i<400;i++){if(await f())return;await Zotero.Promise.delay(100);}throw Error('恢复界面超时');};
 before(async()=>{win=await loadZoteroPane();win.Zotero_Tabs.closeAll();await R.attachWindow(win);});
 after(async()=>{await IOUtils.writeUTF8(PathUtils.join(Zotero.DataDirectory.dir,'material-browser-acceptance','restart-report.json'),JSON.stringify({type:'独立进程重启，真实已保存资产与前台',checks},null,2));win.close();});
 it('restores reviewed topics, image asset, query and custom prompts without regenerating',async()=>{
  const p=Object.values(R.manuscripts.all()).find(p=>p.title==='素材浏览与模板验收');assert.exists(p);assert.isTrue(p.materialCatalog.topics.some(t=>t.kind==='research'));const before=JSON.stringify(p.materialCatalog);await R.notebook.open(p.id);await wait(()=>{frame=win.document.getElementById('research-notebook-'+p.id);doc=frame?.contentDocument;return frame?.contentWindow.NotebookUI?.ready;});assert.exists(doc.querySelector('#topic-navigation [data-topic]'));assert.equal(JSON.stringify(R.manuscripts.get(p.id).materialCatalog),before);assert.equal(doc.getElementById('search').value,R.notebook.query(p.id));assert.equal(R.store.get().promptTemplates[0].name,'检索研究证据');const img=Object.values(R.manuscripts.assetLibrary()).find(m=>m.kind==='image'&&m.generationStatus==='completed');assert.exists(img);await R.notebook.select(p.id,img.id);await wait(()=>doc.querySelector('#detail img')?.naturalWidth>0);checks.push('研究主题、归属、查询、自定义模板、图片和真实中文说明从本机恢复；没有重新调用模型');
 });
 it('opens templates when clicking an already focused input and selects one with Tab',async()=>{const input=doc.getElementById('question'),W=frame.contentWindow;input.value='自动调制识别';input.focus();input.click();await wait(()=>!input.nextElementSibling.hidden);input.dispatchEvent(new W.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.isTrue(input.nextElementSibling.hidden);input.click();assert.isFalse(input.nextElementSibling.hidden);input.dispatchEvent(new W.KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));assert.equal(doc.activeElement.dataset.template,'search');doc.activeElement.click();assert.equal(doc.getElementById('ai-mode').value,'search');assert.equal(input.value,'自动调制识别');checks.push('点击已聚焦的 AI 输入框可重新显示模板；Tab 选择模板后鼠标应用，保留用户问题');});
 it('restores the feasibility plan generated at project creation and the native library item',async()=>{
  const p=Object.values(R.manuscripts.all()).filter(p=>p.title.startsWith('创建即评估')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).find(p=>R.notebook.state(p.id).assessment?.status==='ready');assert.exists(p,'创建时成功评估的项目');const before=R.notebook.state(p.id),itemID=await R.manuscripts.ensureLibraryItem(p.id),item=await Zotero.Items.getAsync(itemID);assert.equal(R.manuscripts.projectForItem(item),p.id);await R.notebook.open(p.id);await wait(()=>{frame=win.document.getElementById('research-notebook-'+p.id);doc=frame?.contentDocument;return frame?.contentWindow.NotebookUI?.ready;});assert.exists(doc.querySelector('.assessment-overview'));assert.isFalse(doc.getElementById('evaluation').hidden);assert.include(doc.getElementById('plan').textContent,'可行性与限制');assert.deepEqual(R.notebook.state(p.id).versions,before.versions);checks.push('创建时生成的可行性方案、待补条件、版本和文库项目入口在新进程恢复，概览可见');
 });
});
