describe('Research notebook persisted workflow',function(){
 this.timeout(60000);let win,ui,frame,doc,R=Zotero.Research,p;const checks=[];
 const wait=async f=>{for(let i=0;i<300;i++){if(f())return;await Zotero.Promise.delay(100);}throw Error('界面未恢复');};
 before(async()=>{win=await loadZoteroPane();win.Zotero_Tabs.closeAll();await R.attachWindow(win);p=Object.values(R.manuscripts.all()).find(p=>p.title==='学术素材验收');assert.exists(p);await R.manuscripts.open(p.id);await wait(()=>{ui=win.document.getElementById('manuscript-'+p.id)?.contentWindow.ManuscriptUI;return ui?.ready;});await R.notebook.open(p.id);await wait(()=>{frame=win.document.getElementById('research-notebook-'+p.id);doc=frame?.contentDocument;return frame?.contentWindow.NotebookUI?.ready;});});
 after(async()=>{await IOUtils.writeUTF8(PathUtils.join(Zotero.DataDirectory.dir,'notebook-acceptance','restart-report.json'),JSON.stringify({type:'独立进程重启后的真实持久化数据和前台 DOM 事件',checks},null,2));win?.close();});
 it('restores source selection, real source answer, plan versions and artifacts after process restart',async()=>{const state=R.notebook.state(p.id);assert.isAbove(state.versions.length,0);assert.isAbove(state.artifacts.length,0);assert.isTrue(state.messages.some(m=>m.channel==='source'&&m.evidence?.length));assert.exists(R.manuscripts.assetLibrary()[state.selectedMaterial]);assert.include(doc.getElementById('artifact-list').textContent,'查看方案');checks.push('重启进程恢复真实问答、来源选择、方案版本和研究产物');});
 it('opens the cited original and drags an actual artifact into editable prose with undo',async()=>{doc.getElementById('read-tab').click();const cite=doc.querySelector('#messages .source-citation');assert.exists(cite);cite.click();const material=R.manuscripts.assetLibrary()[R.notebook.state(p.id).selectedMaterial];await wait(()=>Zotero.Reader._readers.some(r=>r.itemID===material.attachmentID&&!r._isTabClosed));await R.manuscripts.open(p.id);const a=R.notebook.state(p.id).artifacts.at(-1),before=ui.p.blocks.length;const page=ui.$('canvas').querySelector('.paper'),data=new win.DataTransfer();data.setData('application/x-manuscript-material',a.materialID);page.dispatchEvent(new win.DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));assert.equal(ui.p.blocks.length,before+1);const b=ui.p.blocks.at(-1);assert.equal(b.artifactID,a.id);assert.isAbove(b.text.length,200);assert.notInclude(b.text,'**');assert.include(b.text,'\n');assert.isTrue(b.materials.some(m=>m.id===a.materialID));ui.$('canvas').dispatchEvent(new win.KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true}));assert.equal(ui.p.blocks.length,before);await ui.persist();checks.push('点击回答引用打开原始 PDF；拖入产物写入实际可编辑正文且保留稳定来源，Ctrl+Z 恢复');});
 it('marks only related artifacts stale without changing their prose or sources',async()=>{const state=R.notebook.state(p.id),v=state.versions.at(-1),a=state.artifacts.find(a=>a.versionID===v.id);assert.exists(a);const before=R.manuscripts.assetLibrary()[a.materialID];const affected=await R.notebook.invalidateArtifacts(p.id,[v.plan.hypotheses[0].id]);assert.include(affected,a.materialID);const after=R.manuscripts.assetLibrary()[a.materialID];assert.equal(after.sourceText,before.sourceText);assert.equal(after.verification,'stale');assert.equal(after.revision,before.revision+1);assert.deepEqual(R.notebook.state(p.id).versions.at(-1).plan,v.plan);checks.push('假设依赖失效只标记相关产物；正文与既有实验方案内容保持不变');});
});
