describe('Writing real usability and network',function(){
 this.timeout(600000);let win,R=Zotero.Research,ui,frame,projectID,folder,record,attachmentID,home;const report={checks:[],started:new Date().toISOString()};
 const wait=async(fn,ms=240000)=>{const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await Zotero.Promise.delay(150);}throw Error('等待超时：'+ui?.$('status')?.textContent);};
 const click=(host,text)=>{const b=[...host.querySelectorAll('button')].find(x=>x.textContent===text);assert.exists(b,text);b.click();};
 const event=(node,name,args={})=>node.dispatchEvent(new frame.contentWindow[name.includes('key')?'KeyboardEvent':'Event'](name,{bubbles:true,cancelable:true,...args}));
 async function shot(name){await Zotero.Promise.delay(250);const image=await win.browsingContext.currentWindowGlobal.drawSnapshot(null,1,'white'),c=win.document.createElementNS('http://www.w3.org/1999/xhtml','canvas');c.width=image.width;c.height=image.height;c.getContext('2d').drawImage(image,0,0);const b=await new Promise(r=>c.toBlob(r));await IOUtils.write(PathUtils.join(folder,name),new Uint8Array(await b.arrayBuffer()));image.close();}
 async function save(){await IOUtils.writeUTF8(PathUtils.join(folder,'live-report.json'),JSON.stringify(report,null,2));}
 before(async()=>{win=await loadZoteroPane();win.Zotero_Tabs.closeAll();win.focus();await Zotero.Promise.delay(6500);win.resizeTo(1500,1000);await R.attachWindow(win);folder=PathUtils.join(Zotero.DataDirectory.dir,'writing-live');await IOUtils.makeDirectory(folder,{ignoreExisting:true});home=await R.openWorkflow('writing');home.$('new-manuscript').click();home.$('manuscript-name').value='Transformer方法综述 · 真实联调';home.$('manuscript-name').closest('form').dispatchEvent(new (home.$('manuscript-name').ownerDocument.defaultView.Event)('submit',{bubbles:true,cancelable:true}));await wait(()=>{frame=win.document.querySelector('iframe[id^="manuscript-"]');ui=frame?.contentWindow.ManuscriptUI;return ui?.ready;});projectID=ui.p.id;report.projectID=projectID;});
 after(async()=>{report.ended=new Date().toISOString();await save();win?.close();});
 it('writes actual Chinese prose in a plain empty paragraph with a real model and undoes it',async()=>{
  const b=ui.p.blocks[0],node=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);assert.exists(node);assert.notExists(node.closest('.material-frame'));ui.p.memory={goal:'写一段中文方法背景，解释注意力机制如何整合上下文。不写实验结果、不列数字、不虚构引用。'};node.focus();
  const real=R.studio.request;let calls=[];R.studio.request=async(...args)=>{const result=await real(...args);calls.push({model:result.model,cacheHit:result.cacheHit});return result;};
  try{event(node,'keydown',{key:'Tab',ctrlKey:true});await wait(()=>!ui.busy);const current=ui.p.blocks.find(x=>x.id===b.id);assert.isAbove(current.text.length,30,ui.$('status').textContent);assert.match(current.text,/[\u3400-\u9fff]/);assert.equal(win.Zotero_Tabs.selectedType,'manuscript');await shot('01-real-plain-completion.png');report.checks.push({path:'普通段落 Ctrl+Tab',type:'真实模型 + Zotero前台事件',calls,text:current.text});const text=current.text;event(ui.$('canvas'),'keydown',{key:'z',ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,'');event(ui.$('canvas'),'keydown',{key:'y',ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,text);}finally{R.studio.request=real;await save();}
 });
 it('gets a real arXiv paper from the frontend and automatically creates Chinese semantic assets',async()=>{
  home=await R.openWorkflow('search');home.$('search-source').value='arxiv';home.$('search-query').value='1706.03762';home.$('search-academic').click();await wait(()=>!home.$('search-academic').disabled);assert.include(home.$('search-results').textContent,'Attention Is All You Need',home.$('status').textContent);await shot('02-real-arxiv-metadata.png');
  click(home.$('search-results'),'获取并阅读全文');await wait(()=>Zotero.Reader._readers.some(r=>Zotero.Items.get(r.itemID)?.getField('url')?.includes('1706.03762')));const reader=Zotero.Reader._readers.find(r=>Zotero.Items.get(r.itemID)?.getField('url')?.includes('1706.03762'));attachmentID=reader.itemID;assert.equal(win.Zotero_Tabs.selectedType,'reader');await shot('03-real-arxiv-pdf.png');
  await wait(()=>['complete','partial','failed'].includes(R.manuscripts.indexState()[attachmentID]?.status),480000);const state=R.manuscripts.indexState()[attachmentID];report.checks.push({path:'arXiv 编号检索→PDF→自动素材',type:'真实联网 + 真实模型 + Zotero前台',state});await save();assert.equal(state.status,'complete',state.error);assert.isAbove(state.count,0);
  const sources=state.assetIDs.map(id=>R.manuscripts.assetLibrary()[id]);assert.isTrue(sources.every(m=>m.anchors.length&&/[\u3400-\u9fff]/.test(m.summary)));report.assetID=sources[0].id;win.Zotero_Tabs.select(frame.parentElement.id);click(ui.$('left-tabs'),'▧ 素材库');ui.materialQuery=sources[0].title;ui.renderLibrary();assert.include(ui.$('library').textContent,sources[0].summary);await shot('04-auto-chinese-materials.png');
  const before=Object.keys(R.manuscripts.assetLibrary()).length,original=await Zotero.Items.getAsync(attachmentID),duplicate=await Zotero.Attachments.importFromFile({file:Zotero.File.pathToFile(await original.getFilePathAsync()),parentItemID:original.parentID});await wait(()=>R.manuscripts.indexState()[duplicate.id]?.status==='complete');assert.equal(Object.keys(R.manuscripts.assetLibrary()).length,before);report.checks.push({path:'重复导入同一PDF',type:'真实附件导入与素材复用',assetCount:before});await save();
 });
 it('drags a Chinese material into one simple frame and inserts sourced prose with a real model',async()=>{
  const m=R.manuscripts.assetLibrary()[report.assetID];assert.exists(m);win.Zotero_Tabs.select(frame.parentElement.id);ui.materialQuery=m.title;ui.renderLibrary();const card=ui.$('library').querySelector(`[data-material="${m.id}"]`),data=new frame.contentWindow.DataTransfer();card.dispatchEvent(new frame.contentWindow.DragEvent('dragstart',{bubbles:true,dataTransfer:data}));ui.$('canvas').querySelector('.paper').dispatchEvent(new frame.contentWindow.DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));const b=ui.p.blocks.find(x=>x.assembly&&x.materials.some(l=>l.id===m.id));assert.exists(b);ui.selectBlock(b.id);b.requirements='根据关联素材写一段中文方法解释，不写没有证据的实验结果。';const node=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);node.focus();event(node,'keydown',{key:'Tab',ctrlKey:true});await wait(()=>!ui.busy);assert.isAbove(ui.p.blocks.find(x=>x.id===b.id).text.length,30,ui.$('status').textContent);assert.isTrue(ui.p.blocks.find(x=>x.id===b.id).materials.some(l=>l.id===m.id));
  const box=ui.$('canvas').querySelector(`[data-id="${b.id}"]`);assert.equal(box.querySelectorAll('.material-caption').length,1);assert.notExists(box.querySelector('.assembly-card'));const y=box.querySelector('.editable').getBoundingClientRect().top;box.dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));await Zotero.Promise.delay(300);assert.equal(box.querySelector('.editable').getBoundingClientRect().top,y);await shot('05-real-sourced-prose.png');report.checks.push({path:'素材拖放→真实正文与来源',type:'真实模型 + Zotero前台',text:ui.p.blocks.find(x=>x.id===b.id).text});await save();
  click(ui.$('details'),'解除素材框，保留正文');assert.notExists(ui.$('canvas').querySelector(`[data-id="${b.id}"] .material-caption`));assert.isAbove(ui.p.blocks.find(x=>x.id===b.id).text.length,30);
 });
 it('preserves edits during delayed AI replies and keeps Delete scoped to the outline',async()=>{
  click(ui.$('insert-tools'),'论文模块');click(ui.$('popover-content'),'正文');await Zotero.Promise.delay(100);let b=ui.p.blocks.find(x=>x.id===ui.p.ui.blockID),node=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);win.focus();frame.contentWindow.focus();node.focus();node.textContent='我正在整理方法背景。';event(node,'beforeinput');event(node,'input');
  const C=ChromeUtils.importESModule('chrome://zotero/content/research/shared/writing-completion.mjs'),real=R.manuscripts.coauthor;let pending,observed,calls=0;
  R.manuscripts.coauthor=async(p,id,prompt,status,signal,range)=>{calls++;const copy=ui.M.clone(p),block=copy.blocks.find(x=>x.id===id);observed={copy,block,range};pending=Zotero.Promise.defer();await pending.promise;return {proposal:C.completionProposal(copy,block,{text:'注意力机制通过加权整合不同位置的信息，使当前表示能够反映相关的上下文关系。',contentKind:'method_explanation',evidence:[]},range),materials:[],trace:[]};};
  try{
   node.dispatchEvent(new frame.contentWindow.CompositionEvent('compositionstart',{bubbles:true}));event(node,'keydown',{key:'Tab',ctrlKey:true,isComposing:true});assert.equal(calls,0);node.dispatchEvent(new frame.contentWindow.CompositionEvent('compositionend',{bubbles:true}));
   const selection=frame.contentWindow.getSelection(),range=frame.contentDocument.createRange();range.selectNodeContents(node);range.collapse(false);selection.removeAllRanges();selection.addRange(range);assert.equal(frame.contentDocument.activeElement,node,'编辑器获得焦点');assert.isFalse(ui.composing,'输入法组词结束');event(node,'keydown',{key:'Tab',ctrlKey:true});await wait(()=>!!pending,10000);node.textContent+='这是生成期间继续输入的内容。';event(node,'beforeinput');event(node,'input');const edited=node.textContent;pending.resolve();await wait(()=>!ui.busy);assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,edited);assert.exists(ui.$('inline-completion'));click(ui.$('inline-completion'),'插入到当前光标');assert.include(ui.p.blocks.find(x=>x.id===b.id).text,edited);event(ui.$('canvas'),'keydown',{key:'z',ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,edited);
   node=ui.$('canvas').querySelector(`[data-id="${b.id}"] .editable`);node.focus();const selectedRange=frame.contentDocument.createRange();const walker=frame.contentDocument.createTreeWalker(node,frame.contentWindow.NodeFilter.SHOW_TEXT);let leaf;while((leaf=walker.nextNode())&&leaf.length<5){}assert.exists(leaf);selectedRange.setStart(leaf,0);selectedRange.setEnd(leaf,5);selection.removeAllRanges();selection.addRange(selectedRange);pending=null;assert.equal(frame.contentDocument.activeElement,node,'编辑器获得焦点');assert.isFalse(ui.composing,'输入法组词结束');event(node,'keydown',{key:'Tab',ctrlKey:true});await wait(()=>!!pending,10000);pending.resolve();await wait(()=>!ui.busy);assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,edited);click(ui.$('inline-completion'),'接受替换');assert.isTrue(ui.p.blocks.find(x=>x.id===b.id).text.endsWith(edited.slice(5)));event(ui.$('canvas'),'keydown',{key:'z',ctrlKey:true});assert.equal(ui.p.blocks.find(x=>x.id===b.id).text,edited);
   click(ui.$('left-tabs'),'☷ 论文结构');const outline=ui.$('library').querySelector(`[data-outline-block="${b.id}"]`);outline.click();outline.focus();const assets=Object.keys(R.manuscripts.assetLibrary()).length;event(outline,'keydown',{key:'Delete'});assert.notExists(ui.p.blocks.find(x=>x.id===b.id));event(ui.$('canvas'),'keydown',{key:'z',ctrlKey:true});assert.exists(ui.p.blocks.find(x=>x.id===b.id));assert.equal(Object.keys(R.manuscripts.assetLibrary()).length,assets);
   ui.$('library').dispatchEvent(new frame.contentWindow.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:30,clientY:180}));assert.include(ui.$('assembly-context').textContent,'添加章节');event(ui.$('assembly-context'),'keydown',{key:'Escape'});await shot('07-outline-and-conflict.png');report.checks.push({path:'选区替换、并发输入冲突、IME事件保护、Delete与撤销',type:'受控回复 + 真实Zotero界面事件；非真实输入法候选窗'});await save();
  }finally{pending?.resolve();ui.abort?.abort();R.manuscripts.coauthor=real;await Zotero.Promise.delay(100);}
 });
 it('restores panel sizes, checks evidence and exports real prose as editable Word',async()=>{
  click(ui.$('insert-tools'),'表格');ui.$('grid').querySelector('[data-row="2"][data-col="2"]').click();await Zotero.Promise.delay(100);
  const csv=PathUtils.join(folder,'attention-symbols.csv');await IOUtils.writeUTF8(csv,'符号,作用\nQ,当前位置查询\nK,上下文匹配\nV,上下文内容\n');const dataPicker=sinon.stub(R,'pick').resolves(csv);try{click(ui.$('details'),'从文件选择数据');await wait(()=>ui.p.blocks.some(b=>b.table?.binding));}finally{dataPicker.restore();}
  const table=ui.p.blocks.find(b=>b.table?.binding);ui.selectBlock(table.id);const caption=[...ui.$('details').querySelectorAll('label')].find(x=>x.textContent.startsWith('表题')).querySelector('input');caption.value='注意力机制符号说明';event(caption,'change');
  click(ui.$('insert-tools'),'公式');await Zotero.Promise.delay(100);const latex=ui.$('details').querySelector('textarea');latex.value='\\operatorname{Attention}(Q,K,V)=\\operatorname{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V';event(latex,'change');
  click(ui.$('insert-tools'),'引用');await wait(()=>ui.$('popover-content').querySelector('button'));ui.$('popover-content').querySelector('button').click();await Zotero.Promise.delay(100);
  ui.p.ui.leftWidth=270;ui.p.ui.rightWidth=300;ui.p.ui.aiHeight=260;await ui.persist();await R.store.flush();const id=ui.p.id;win.Zotero_Tabs.close(frame.parentElement.id);await Zotero.Promise.delay(200);await R.manuscripts.open(id);await wait(()=>{frame=win.document.getElementById('manuscript-'+id);ui=frame?.contentWindow.ManuscriptUI;return ui?.ready;});assert.equal(ui.p.ui.leftWidth,270);assert.equal(ui.p.ui.rightWidth,300);
  const pick=sinon.stub(R,'pick').resolves(folder);try{ui.$('export').click();await wait(()=>ui.lastExport||!ui.busy&&(ui.$('status').classList.contains('error')||ui.$('popover').open));assert.exists(ui.lastExport,ui.$('popover').textContent+' '+ui.$('status').textContent);report.docx=ui.lastExport.path;await shot('06-real-prose-export.png');}finally{pick.restore();}report.checks.push({path:'恢复布局→导出实际正文',type:'Zotero前台 + DOCX产物',docx:report.docx});await save();
 });
});
