import {placeOnPaper,addAfter} from './editor-interactions.mjs';
/* SPDX-License-Identifier: AGPL-3.0-or-later */
import {U,$,el,button,field,modal,status,snapshot,changed,persist,selected,selectBlock,attachMaterial,renderEvidence,verifyBlock,openMaterial} from './main.mjs';
import {renderAssembly,captureRange,completeBlock} from './assembly-tools.mjs';
import {paragraphAction} from './writing-tools.mjs';
import {renderTable,tableDetails} from './table.mjs';
import {sliceRuns} from '../shared/richtext.mjs';
export async function insertBlock(type,extra={}){
 const b=U.M.block(type,U.p.ui.sectionID,extra);
 if(type==='image'){b.imagePath=await U.A.image();if(!b.imagePath)return;}
 if(type==='citation'){const box=modal('插入 Zotero 引用');const items=await U.E.library.selection();const ids=new Set(U.p.materialPaperIDs||[]);for(const item of items){const id=item.id||item.itemID;if(id)ids.add(id);}for(const m of U.p.materials)if(m.citationItemID)ids.add(m.citationItemID);if(!ids.size){box.append(el('p','先在 Zotero 文库中选择要引用的论文，或导入带来源的笔记素材。'));return;}for(const id of ids){const item=await window.parent.Zotero.Items.getAsync(id);if(item?.isRegularItem())button(item.getField('title'),()=>{add({...b,citationItemID:id,text:item.getField('title')});$('popover').close();},box);}return;}
 add(b);
}
function add(b){snapshot();const index=U.p.blocks.findIndex(x=>x.id===U.p.ui.blockID);U.p.blocks.splice(index<0?U.p.blocks.length:index+1,0,b);U.p.ui.blockID=b.id;changed({editor:true});document.querySelector(`[data-id="${b.id}"] .editable`)?.focus();}
function captureCaret(node,b){const selection=window.getSelection();if(!selection.rangeCount||!node.contains(selection.anchorNode))return;const range=selection.getRangeAt(0).cloneRange();range.selectNodeContents(node);range.setEnd(selection.anchorNode,selection.anchorOffset);U.p.ui.caret=range.toString().length;U.p.ui.blockID=b.id;}
function readRuns(node){const runs=[];const visit=(n,marks={})=>{if(n.nodeType===3){runs.push({text:n.textContent,...marks});return;}const tag=n.nodeName.toLowerCase(),next={...marks};if(['b','strong'].includes(tag))next.bold=true;if(['i','em'].includes(tag))next.italic=true;if(tag==='u')next.underline=true;if(tag==='sup')next.sup=true;if(tag==='sub')next.sub=true;if(n.style?.color)next.color=n.style.color;if(n.getAttribute?.('color'))next.color=n.getAttribute('color');if(n.style?.fontFamily)next.fontFamily=n.style.fontFamily;if(n.getAttribute?.('face'))next.fontFamily=n.getAttribute('face');if(tag==='br'){runs.push({text:'\n'});return;}if(['div','p'].includes(tag)&&runs.length)runs.push({text:'\n'});for(const child of n.childNodes)visit(child,next);};for(const child of node.childNodes)visit(child);return runs;}
function showTextTools(node,b){U.textSelection=null;const selection=window.getSelection();document.getElementById('selection-tools')?.remove();if(selection.isCollapsed||!node.contains(selection.anchorNode))return;const range=selection.getRangeAt(0).cloneRange(),bar=el('div',undefined,'row');bar.id='selection-tools';const prefix=range.cloneRange();prefix.selectNodeContents(node);prefix.setEnd(range.startContainer,range.startOffset);const start=prefix.toString().length,text=range.toString();if(b.text.slice(start,start+text.length)===text)U.textSelection={blockID:b.id,start,end:start+text.length,text};for(const [purpose,label] of [['polish','润色选中文字'],['evidence','补充证据']])button(label,()=>paragraphAction(purpose),bar);const more=el('details');more.append(el('summary','格式'));bar.append(more);for(const [command,label]of [['bold','加粗'],['italic','斜体'],['underline','下划线'],['superscript','上标'],['subscript','下标']]){const btn=button(label,()=>{selection.removeAllRanges();selection.addRange(range);snapshot();document.execCommand(command);node.dispatchEvent(new Event('input',{bubbles:true}));bar.remove();},more);btn.onmousedown=e=>e.preventDefault();}$('details').prepend(bar);}
function restoreCaret(node,count){const walker=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);let text;while((text=walker.nextNode())){if(count<=text.length){const r=document.createRange();r.setStart(text,count);r.collapse(true);const s=window.getSelection();s.removeAllRanges();s.addRange(r);return;}count-=text.length;}}
export function renderEditor(){
 const canvas=$('canvas'),scroll=U.p.ui.scrollTop;canvas.replaceChildren();let pageNumber=0;
 for(const section of U.p.sections){let page;const newPage=()=>{page=el('article',undefined,'paper');page.dataset.page=String(++pageNumber);page.dataset.section=section.id;page.append(el('h2',section.title+(pageNumber>1&&page?.continued?'（续）':'')));canvas.append(page);page.style.zoom=U.p.ui.paperZoom||1;page.ondragover=e=>{if(e.dataTransfer.types.some(t=>t.startsWith('application/x-manuscript-')))e.preventDefault();};page.ondrop=e=>placeOnPaper(e.currentTarget,e);};newPage();
  const blocks=U.p.blocks.filter(b=>b.sectionID===section.id);if(!blocks.length){const b=U.M.block('paragraph',section.id,{emptyStarter:true});U.p.blocks.push(b);blocks.push(b);}
  for(const b of blocks){const node=el('section',undefined,`block block-${b.type}${b.id===U.p.ui.blockID?' selected':''}`);node.dataset.id=b.id;node.dataset.review=b.review;node.tabIndex=0;node.onclick=()=>{if(U.previewMaterialID||U.p.ui.blockID!==b.id){U.selectedCells=[];selectBlock(b.id);}};
   node.ondragover=e=>{if(!e.dataTransfer.types.some(t=>t.startsWith('application/x-manuscript-')))return;e.preventDefault();const rect=node.getBoundingClientRect(),after=e.clientY>rect.top+rect.height/2;node.classList.toggle('block-drop-after',after);node.classList.toggle('block-drop-before',!after);};node.ondragleave=()=>node.classList.remove('block-drop-after','block-drop-before');node.ondrop=e=>placeOnPaper(node.closest('.paper'),e);
   const badge=el('span',b.review==='stale'?'来源变化 · 需要重新核验':b.claim?'论点 · '+(b.review==='verified'?'已核验':'待核验'):b.type==='table'?'实验表格':b.type==='formula'?'可编辑公式':'','badge');badge.draggable=true;badge.title='拖动以调整模块顺序';badge.ondragstart=e=>e.dataTransfer.setData('application/x-manuscript-block',b.id);node.append(badge);
   if(b.type==='table')renderTable(node,b);
   else if(b.type==='image'){const img=el('img');img.alt=b.text||'论文图片';U.E.previewImage(b.imagePath).then(src=>img.src=src).catch(()=>{img.alt='图片无法读取，请替换文件';});node.append(img);editable(node,b,'图片说明与来源');}
   else if(b.type==='citation')node.append(el('span','〔Zotero 引用〕'+b.text));
   else if(b.type==='formula'){const view=el('div');try{window.katex.render(b.text||'\\square',view,{throwOnError:true,displayMode:true});}catch(e){view.textContent='公式尚未解析：'+b.text;}node.append(view);}
   else if(b.type==='crossref')node.append(el('span','↗ '+b.text));
   else {if(['paragraph','heading','list'].includes(b.type))renderAssembly(node,b,U.p.blocks.indexOf(b));editable(node,b,b.type==='placeholder'?'待补：实验设置、数值或引用…':'直接写正文，或按 Ctrl+Tab 开始撰写…');}
   node.style.marginTop=(b.spaceBefore||0)+'pt';node.dataset.pageBreak=String(!!b.pageBreakBefore);if(b.pageBreakBefore&&page.querySelector('.block'))newPage();page.append(node);if(b.assembly&&b.materials.length){const after=button('在素材下方写正文',()=>addAfter(b),node,'after-material');after.setAttribute('aria-label','在素材下方添加段落');}if(page.scrollHeight>1125&&page.querySelectorAll('.block').length>1){node.remove();newPage();page.append(node);}
  }
 }
 canvas.scrollTop=scroll;const active=canvas.querySelector(`[data-id="${U.p.ui.blockID}"] .editable`);if(active&&U.p.ui.caret){restoreCaret(active,U.p.ui.caret);}renderDetails();
}
function editable(host,b,placeholder){const n=el(b.type==='list'?'ul':'div',undefined,'editable');n.contentEditable=b.locked?'false':'true';n.dataset.placeholder=placeholder;n.setAttribute('role','textbox');n.setAttribute('aria-label',b.type==='heading'?'编辑标题':'编辑模块正文');if(b.type==='list'){for(const line of (b.text||'').split('\n'))n.append(el('li',line));}else if(b.runs?.length){for(const r of b.runs){let span=el('span',r.text);if(r.color)span.style.color=r.color;if(r.fontFamily)span.style.fontFamily=r.fontFamily;for(const [key,tag]of [['bold','strong'],['italic','em'],['underline','u'],['sup','sup'],['sub','sub']])if(r[key]){const outer=el(tag);outer.append(span);span=outer;}n.append(span);}}else n.textContent=b.text||'';
 n.onfocus=()=>{U.lastTyping=0;if(U.previewMaterialID||U.p.ui.blockID!==b.id)selectBlock(b.id);};
 n.onkeydown=e=>{if(e.key==='Enter'&&b.type!=='list'&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.isComposing&&!U.composing){e.preventDefault();const r=captureRange(b);snapshot();const rest=b.text.slice(r.end),runs=b.runs||[{text:b.text}],afterRuns=sliceRuns(runs,r.end,b.text.length);b.runs=sliceRuns(runs,0,r.start);b.text=b.text.slice(0,r.start);b.revision++;const next=U.M.block('paragraph',b.sectionID,{text:rest,runs:afterRuns});U.p.blocks.splice(U.p.blocks.indexOf(b)+1,0,next);U.p.ui.blockID=next.id;U.p.ui.caret=0;changed({editor:true});document.querySelector(`[data-id="${next.id}"] .editable`)?.focus();}};n.onbeforeinput=()=>{if(U.formatting)return;U.textSelection=null;if(U.typingBlock!==b.id||!U.lastTyping||Date.now()-U.lastTyping>1000)snapshot();U.lastTyping=Date.now();U.typingBlock=b.id;};n.oninput=()=>{b.emptyStarter=false;delete b.aiInsertions;if(b.type==='list')b.text=[...n.children].map(x=>x.textContent).join('\n');else{b.runs=readRuns(n);b.text=b.runs.map(r=>r.text).join('');}b.review=b.claim?'missing':b.review;b.revision++;captureCaret(n,b);persist();if(n.closest('.paper').scrollHeight>1125)status('当前页内容较长；完成编辑后将重新分页。');};n.onkeyup=()=>{captureCaret(n,b);persist();};n.onmouseup=()=>{captureCaret(n,b);persist();showTextTools(n,b);};n.onpaste=e=>{e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));};if(b.aiInsertions?.length){const walker=document.createTreeWalker(n,NodeFilter.SHOW_TEXT),nodes=[];let t,offset=0;while((t=walker.nextNode()))nodes.push(t);for(const textNode of nodes){const value=textNode.textContent,fragment=document.createDocumentFragment();let at=0;for(const range of b.aiInsertions){const start=Math.max(0,range.start-offset),end=Math.min(value.length,range.end-offset);if(end<=start)continue;fragment.append(document.createTextNode(value.slice(at,start)),el('mark',value.slice(start,end),'ai-added'));at=end;}fragment.append(document.createTextNode(value.slice(at)));offset+=value.length;textNode.replaceWith(fragment);}}host.append(n);}
export function renderDetails(){const host=$('details'),b=selected();host.replaceChildren();if(!b){host.append(el('h3','选择一个模块'),el('p','点击正文、表格或图片，即可看到相关工具和来源。','empty'));return;}host.append(el('h3',({table:'表格',formula:'公式',image:'图片',citation:'引用',placeholder:'待填卡',heading:'小标题',list:'列表'})[b.type]||'正文模块'));
 const preview=el('div',undefined,'object-preview');
 if(b.type==='formula'){try{window.katex.render(b.text||'\\square',preview,{displayMode:true,throwOnError:true});}catch(_){preview.textContent='公式暂不能解析，请检查下方 LaTeX。';}host.append(preview);}
 if(b.type==='image'){const img=el('img');img.alt=b.text||'图片预览';preview.append(img);host.append(preview);U.E.previewImage(b.imagePath).then(src=>img.src=src).catch(()=>img.alt='图片暂不能读取');}
 if(b.type==='table'){const table=el('table');for(const [i,row] of b.table.rows.entries()){const tr=el('tr');for(const cell of row){if(cell.hidden)continue;const td=el(i?'td':'th',cell.text);td.rowSpan=cell.rowspan;td.colSpan=cell.colspan;td.style.verticalAlign=cell.vertical;tr.append(td);}table.append(tr);}preview.append(table);host.append(preview);}
 if(b.type==='table')tableDetails(host,b);
 else if(b.type==='formula'){field(host,'LaTeX 公式',b.text,v=>{snapshot();b.text=v;changed({editor:true});},'textarea');host.append(el('p','预览用于阅读；导出使用 OMML，可在 Word 公式工具中继续编辑。','muted'));}
 else if(b.type==='image'){field(host,'图注',b.text,v=>{snapshot();b.text=v;changed({editor:true});});button('替换图片',async()=>{const path=await U.A.image();if(path){snapshot();b.imagePath=path;changed({editor:true});}},host);}
 else if(b.type==='placeholder')button('转为正文并填写',()=>{snapshot();b.type='paragraph';changed({editor:true});},host);
 if(!['table','image','formula','citation'].includes(b.type)){const actions=el('div',undefined,'row');const complete=button('补全当前段落',()=>completeBlock(),actions,'primary');complete.onmousedown=e=>e.preventDefault();if(b.text.trim())button('润色',()=>paragraphAction('polish'),actions);host.append(actions);const aiMore=el('details');aiMore.append(el('summary','更多'));button('补充证据',()=>paragraphAction('evidence'),aiMore);for(const [purpose,name]of [['shorten','精简'],['expand','扩写'],['restructure','重组'],['translate','翻译'],['terms','解释术语']])button(name,()=>paragraphAction(purpose),aiMore);button(b.locked?'解锁此段':'锁定此段',()=>{snapshot();b.locked=!b.locked;changed({editor:true});},aiMore);host.append(aiMore);const setup=el('details');setup.append(el('summary','篇幅与写作要求'));host.append(setup);field(setup,'写作目标（单独保存，不导出正文）',b.requirements,v=>{b.requirements=v;persist();},'textarea');const target=field(setup,'目标篇幅（字）',b.targetWords,v=>{b.targetWords=Math.max(30,Number(v)||300);persist();});target.type='number';const claim=el('label'),checkbox=el('input');checkbox.type='checkbox';checkbox.checked=b.claim;checkbox.onchange=()=>{b.claim=checkbox.checked;changed();};claim.append(checkbox,document.createTextNode('包含需要证据支持的结果或论点'));setup.append(claim);}
 if(b.materials.length)button('解除素材框，保留正文',()=>{snapshot();b.hideMaterialFrame=true;changed({editor:true});},host);
 const sources=el('details');sources.open=b.materials.length>0;sources.append(el('summary',`来源与素材 · ${b.materials.length}`));host.append(sources);
 for(const link of b.materials){const m=U.p.materials.find(m=>m.id===link.id);if(!m)continue;button(m.title,()=>openMaterial(m),sources);const roles=el('details');roles.append(el('summary',({primary:'主要素材',support:'辅助素材',reference:'参考方向'})[link.role]+' · 调整用途'));sources.append(roles);const row=el('div',undefined,'row');for(const [role,title]of [['primary','主要素材'],['support','辅助素材'],['reference','参考方向']])button(title,()=>{link.role=role;changed();},row,link.role===role?'active':'');roles.append(row);}
 if(!b.materials.length)sources.append(el('p','将素材卡拖入此模块，即可建立来源链。','muted'));
 if(b.materials.length){const chain=el('details');chain.append(el('summary','展开证据链'));sources.append(chain);renderEvidence(chain,b);button('核验来源',()=>verifyBlock(b),sources);}
 const more=el('details');more.append(el('summary','模块操作'));host.append(more);button('删除模块',()=>{if(b.locked)throw Error('此段已锁定，请先解锁');snapshot();U.p.blocks=U.p.blocks.filter(x=>x.id!==b.id);U.p.ui.blockID=null;changed({editor:true});status('已删除模块，可按 Ctrl+Z 撤销。');},more);button('在此后添加段落',()=>insertBlock('paragraph'),more);button('恢复上一个版本',()=>{if(!U.undo.length)throw Error('还没有可恢复版本');U.redo.push(U.M.clone(U.p));U.p=U.undo.pop();changed({editor:true});},more);
}
