import {formatSelection,breakParagraph} from './editor-interactions.mjs';
import {U,$,el,button,field,modal,status,snapshot,changed,persist,selectBlock} from './main.mjs';
export function history(redo=false){const preferOutline=!!document.activeElement?.closest('[data-outline-block],.section-card,[data-material]');const from=redo?U.redo:U.undo,to=redo?U.undo:U.redo;if(!from.length)return;to.push(U.M.clone(U.p));U.p=from.pop();U.lastTyping=0;U.textSelection=null;changed({editor:true});const outline=document.querySelector(`[data-outline-block="${U.p.ui.blockID}"]`),editor=document.querySelector(`[data-id="${U.p.ui.blockID}"] .editable`)||document.querySelector(`[data-id="${U.p.ui.blockID}"] .cell-editor`);(preferOutline?outline||editor:editor||outline)?.focus();status(redo?'已重做':'已撤销；来源资料未改变');}
function selection(){const ids=U.p.ui.selectedBlocks||[];return ids.length?ids:[U.p.ui.blockID].filter(Boolean);}
export function removeSelection(target){
 const section=target.closest('[data-section].section-card'),material=target.closest('[data-material]');
 if(section){const s=U.p.sections.find(s=>s.id===section.dataset.section),box=modal('移除章节');box.append(el('p',`将移除“${s.title}”及其子模块。素材库和 Zotero 文献保留，可按 Ctrl+Z 撤销。`));button('移除章节及子模块',()=>{snapshot();const ids=new Set([s.id]);let added=true;while(added){added=false;for(const x of U.p.sections)if(ids.has(x.parentID)&&!ids.has(x.id)){ids.add(x.id);added=true;}}U.p.sections=U.p.sections.filter(x=>!ids.has(x.id));U.p.blocks=U.p.blocks.filter(b=>!ids.has(b.sectionID));U.p.ui.sectionID=U.p.sections[0]?.id||null;U.p.ui.blockID=null;$('popover').close();changed({editor:true});$('canvas').focus();},box);return;}
 snapshot();if(material){const id=material.dataset.material;U.p.materials=U.p.materials.filter(m=>m.id!==id);for(const b of U.p.blocks)if(b.materials.some(m=>m.id===id)){b.materials=b.materials.filter(m=>m.id!==id);b.review='missing';}U.p.ui.materialID=null;}
 else{const ids=selection();if(U.p.blocks.some(b=>ids.includes(b.id)&&b.locked)){U.undo.pop();throw Error('所选模块已锁定，请先解锁');}U.p.blocks=U.p.blocks.filter(b=>!ids.includes(b.id));U.p.ui.blockID=null;U.p.ui.selectedBlocks=[];}
 changed({editor:true});$('canvas').focus();status('已从当前稿件移除。Ctrl+Z 恢复；原始资料保留。');
}
export function outlineBlock(host,b){const n=button((b.locked?'🔒 ':'¶ ')+(b.title||b.text||b.table?.caption||({paragraph:'空白正文',heading:'小标题',list:'列表',formula:'公式',image:'图片',citation:'引用',table:'表格',placeholder:'待补内容'})[b.type]||'正文').slice(0,35),e=>{const ids=e.ctrlKey?new Set(U.p.ui.selectedBlocks||[]):new Set();if(ids.has(b.id))ids.delete(b.id);else ids.add(b.id);U.p.ui.selectedBlocks=[...ids];selectBlock(b.id,{scroll:true,preserveSelection:true});for(const x of document.querySelectorAll('[data-outline-block]'))x.classList.toggle('selected',ids.has(x.dataset.outlineBlock));},host,'outline-block');n.dataset.outlineBlock=b.id;n.classList.toggle('selected',(U.p.ui.selectedBlocks||[]).includes(b.id));return n;}
export function installKeyboard(){
 let composing=false;document.addEventListener('compositionstart',()=>{composing=true;U.composing=true;});document.addEventListener('compositionend',()=>{composing=false;U.composing=false;});
 document.addEventListener('keydown',e=>{try{
  if(e.isComposing||composing||e.keyCode===229)return;
  const t=e.target,form=t.closest('input,textarea,select'),editable=t.closest('[contenteditable=true]'),cmd=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();
  if(cmd&&key==='s'){e.preventDefault();e.stopPropagation();persist();return;}
  if(e.key==='Escape'&&U.busy){e.preventDefault();U.abort?.abort();return;}
  if(e.key==='Escape'){if($('popover').open)$('popover').close();else{U.p.ui.selectedBlocks=[];U.selectedCells=[];U.p.ui.blockID=null;changed();}return;}
  if(U.handleCompletionKey?.(e))return;
  if(form)return;
  if(cmd&&(key==='z'||key==='y')){e.preventDefault();e.stopPropagation();history(key==='y'||e.shiftKey);return;}
  if(cmd&&key==='f'){e.preventDefault();const box=modal('搜索当前论文'),input=field(box,'查找文字','',()=>{}),results=el('div');box.append(results);input.oninput=()=>{results.replaceChildren();if(!input.value.trim())return;for(const b of U.p.blocks.filter(b=>(b.text||JSON.stringify(b.table||{})).includes(input.value)))button((b.text||b.table?.caption||'表格').slice(0,80),()=>{$('popover').close();selectBlock(b.id,{scroll:true,preserveSelection:true});},results);};input.focus();return;}
  if(e.key==='Delete'&&U.selectedCells.length>1&&t.closest('.table-wrap')){e.preventDefault();snapshot();const b=U.p.blocks.find(b=>b.id===U.p.ui.blockID);for(const x of U.selectedCells)b.table.rows[x.r][x.c].text='';b.review='stale';changed({editor:true});return;}
  if(editable?.classList.contains('editable')&&cmd&&['b','i','u'].includes(key)){e.preventDefault();e.stopPropagation();formatSelection({b:'bold',i:'italic',u:'underline'}[key]);return;}
  if(editable?.classList.contains('editable')&&cmd&&e.key==='Enter'){e.preventDefault();e.stopPropagation();breakParagraph(U.p.blocks.find(b=>b.id===editable.closest('.block').dataset.id));return;}
  if(editable)return;
  const outline=t.closest('[data-outline-block]'),section=t.closest('.section-card'),material=t.closest('[data-material]'),block=t.closest('.block');
  if(cmd&&key==='a'&&(outline||section)){e.preventDefault();e.stopPropagation();U.p.ui.selectedBlocks=U.p.blocks.map(b=>b.id);for(const n of document.querySelectorAll('[data-outline-block]'))n.classList.add('selected');if(section)document.querySelector('[data-outline-block]')?.focus();persist();status(U.p.ui.selectedBlocks.length?'已选中全部稿件模块；Delete 移除，Ctrl+Z 恢复':'当前稿件没有可选择的模块');return;}
  if(e.key==='Delete'&&(outline||section||material||block)){e.preventDefault();removeSelection(t);return;}
  if(e.key==='F2'&&(outline||section)){e.preventDefault();const object=outline?U.p.blocks.find(b=>b.id===outline.dataset.outlineBlock):U.p.sections.find(s=>s.id===section.dataset.section);const box=modal('重命名'),input=field(box,'名称',object.title||'',()=>{});button('保存名称',()=>{snapshot();object.title=input.value.trim();changed({editor:true});$('popover').close();},box);input.focus();return;}
  if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)&&(outline||section)){e.preventDefault();snapshot();const items=outline?U.p.blocks:U.p.sections,id=outline?.dataset.outlineBlock||section.dataset.section,index=items.findIndex(x=>x.id===id),next=index+(e.key==='ArrowUp'?-1:1);if(next>=0&&next<items.length){const object=items.splice(index,1)[0];if(outline)object.sectionID=items[next>index?next-1:next]?.sectionID||object.sectionID;items.splice(next,0,object);}changed({editor:true});document.querySelector(outline?`[data-outline-block="${id}"]`:`.section-card[data-section="${id}"]`)?.focus();return;}
  if(cmd&&['c','x','v'].includes(key)&&(outline||block||t===$('canvas'))){e.preventDefault();if(key==='v'){if(!U.blockClipboard?.length)return;snapshot();const copies=U.M.clone(U.blockClipboard),map=new Map(copies.map(b=>[b.id,U.M.id('block')]));for(const b of copies){b.id=map.get(b.id);b.sectionID=U.p.ui.sectionID;b.dependsOn=b.dependsOn?.map(id=>map.get(id)||id);b.materials=b.materials.filter(x=>U.p.materials.some(m=>m.id===x.id));U.p.blocks.push(b);}changed({editor:true});}else{U.blockClipboard=U.M.clone(U.p.blocks.filter(b=>selection().includes(b.id)));if(key==='x')removeSelection(t);else status('已复制模块和引用关系；可在当前稿件中粘贴。');}}
 }catch(err){status(err.message,true);}});
}
