import {installPromptTemplates} from '../shared/prompt-templates.mjs';
import {installModePicker,resolveMode,materialPreview} from '../shared/material-browser.mjs';
/* SPDX-License-Identifier: AGPL-3.0-or-later */
import * as M from '../shared/manuscript-model.mjs';
import {renderEditor,insertBlock,renderDetails} from './editor.mjs';
import {installKeyboard,outlineBlock} from './keyboard.mjs';
import {themeLibrary,paragraphAction} from './writing-tools.mjs';
import {installAssembly,completeBlock} from './assembly-tools.mjs';
import {renderMaterialLibrary} from './material-library.mjs';
import {installEditorInteractions} from './editor-interactions.mjs';
import {tablePicker} from './table.mjs';
export const $=id=>document.getElementById(id);
export const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
export const U={E:window.parent.Zotero.Research,M,$,el,ready:false,p:null,selectedCells:[],undo:[],redo:[],saving:Promise.resolve(),busy:false};
export function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);const notice=$('ai-notice');if(notice){notice.hidden=!(error&&U.p?.ui.aiOpen);if(!notice.hidden)notice.textContent=text;}}
export function button(text,fn,host,cls){const b=el('button',text,cls);b.type='button';b.onclick=async e=>{try{await fn(e);}catch(err){status(err.message,true);}};host?.append(b);return b;}
export function field(host,label,value,fn,type='input'){const l=el('label',label),input=el(type);input.value=value??'';input.onchange=()=>{try{fn(input.value);}catch(e){status(e.message,true);}};l.append(input);host.append(l);return input;}
export function modal(title){const box=$('popover-content');box.replaceChildren(el('h2',title));$('popover').showModal();return box;}
export function snapshot(){U.undo.push(M.clone(U.p));U.undo=U.undo.slice(-30);U.redo=[];}
export function changed({editor=false}={}){persist();renderNavigation();if(editor)renderEditor();renderDetails();}
export function persist(){
 $('save-status').textContent='保存中…';U.pendingSave=M.clone(U.p);
 if(U.saveWorker)return U.saving;U.saveWorker=true;
 U.saving=(async()=>{await new Promise(resolve=>setTimeout(resolve,100));while(U.pendingSave){const value=U.pendingSave;U.pendingSave=null;value.revision=U.savedRevision;const saved=await U.A.save(value);U.savedRevision=saved.revision;U.p.revision=saved.revision;U.E.notebook?.catalogChanged(U.p.id);}U.saveError=null;$('save-status').textContent='已保存到本机';})().catch(e=>{$('save-status').textContent='保存失败';status(e.message,true);U.saveError=e;}).finally(()=>{U.saveWorker=false;});return U.saving;
}
export function selectBlock(id,{scroll=false,preserveSelection=false}={}){
 if(id){
  const clear=U.previewMaterialID||U.E.notebook.state(U.p.id).selectedMaterial;
  U.previewMaterialID=null;U.p.ui.materialID=null;
  if(clear){U.clearingMaterialSelection=true;U.E.notebook.update(U.p.id,{selectedMaterial:null}).catch(e=>status(e.message,true)).finally(()=>{U.clearingMaterialSelection=false;});}
 }
 if(!preserveSelection)U.p.ui.selectedBlocks=id?[id]:[];
 if(U.textSelection?.blockID!==id)U.textSelection=null;U.p.ui.blockID=id;
 const b=U.p.blocks.find(x=>x.id===id);if(b)U.p.ui.sectionID=b.sectionID;
 for(const n of document.querySelectorAll('.block'))n.classList.toggle('selected',n.dataset.id===id);
 renderDetails();renderChat();persist();
 if(scroll)document.querySelector('[data-id="'+id+'"]')?.scrollIntoView({block:'center'});
}
export function selected(){return U.p.blocks.find(b=>b.id===U.p.ui.blockID);}
function openCoauthor(){if(!U.p.ui.aiOpen){U.p.ui.aiOpen=true;applyPanels();persist();}renderChat();}
function closeCoauthor(){document.activeElement?.closest('#ai')&&document.activeElement.blur();U.p.ui.aiOpen=false;$('ai-prompt').style.height='';applyPanels();persist();}
export function applyPanels(){const s=U.p.ui;$('left').hidden=!s.leftOpen;$('right').hidden=!s.rightOpen;$('ai').hidden=false;$('ai').classList.toggle('collapsed',!s.aiOpen);$('ai-history').hidden=!s.aiOpen;$('toggle-ai').textContent=s.aiOpen?'⌄ 收起对话':'⌃ AI 共创';$('toggle-ai').setAttribute('aria-expanded',String(!!s.aiOpen));$('left').style.width=s.leftWidth+'px';$('right').style.width=s.rightWidth+'px';$('ai').style.height=(s.aiOpen?Math.max(280,s.aiHeight):60)+'px';}
export function renderNavigation(){
 $('project-title').textContent=U.p.title;$('steps').replaceChildren();['选素材','装配','核证据','成文'].forEach((name,i)=>button(`${i+1} ${name}`,async()=>{U.p.ui.step=i;changed();if(i===2)await check();},$('steps'),U.p.ui.step===i?'active':''));
 $('recommendation').replaceChildren();const texts=['把笔记、批注和实验整理成素材，再拖到章节。','拖入素材开始装配；选中对象后，右侧会出现相关工具。','逐条核对来源，数据变化时正文会保留并提示重新核验。','检查通过后，可预览 Word 或导出 DOCX。'];$('recommendation').append(el('span',texts[U.p.ui.step]));
 button(['按主题自动整理素材',selected()?'结合素材补全正文':'插入论文模块','核对当前模块','检查并导出'][U.p.ui.step],()=>[()=>themeLibrary(),()=>selected()?completeBlock():insertBlock('paragraph',{assembly:true}),()=>verifyBlock(selected()),()=>exportDoc(false)][U.p.ui.step](),$('recommendation'),'primary').hidden=U.p.ui.left==='materials'&&U.p.ui.step===0;
 $('left-tabs').replaceChildren();for(const [key,name]of [['materials','▧ 素材库'],['structure','☷ 论文结构'],['evidence','◇ 证据网络']])button(name,()=>{U.p.ui.left=key;renderNavigation();persist();},$('left-tabs'),U.p.ui.left===key?'active':'');
 for(const b of $('left-tabs').children){b.setAttribute('role','tab');b.setAttribute('aria-selected',String(b.classList.contains('active')));}$('left-tabs').setAttribute('role','tablist');
 renderLibrary();
}
export function attachMaterial(b,id,role='primary'){b.hideMaterialFrame=false;let m=U.p.materials.find(m=>m.id===id);if(!m){const shared=U.A.assetLibrary()[id];if(!shared)return;m=M.clone(shared);U.p.materials.push(m);}if(!b.materials.some(x=>x.id===id))b.materials.push({id,role,revision:m.revision});if(!b.text.trim()&&['paragraph','placeholder'].includes(b.type)){if(m.imagePath){b.type='image';b.imagePath=m.imagePath;b.text=U.A.summaryFor(m);}else if(m.data?.rows?.length){b.type='table';M.bindTable(U.p,b,m);}}if(m.artifactID&&!b.text.trim()){const rendered=el('div');U.E.renderContent(rendered,m.sourceText);b.text=U.E.contentRenderer(document).plainText(rendered);b.artifactID=m.artifactID;}b.review='missing';}
export function renderLibrary(){
 const host=$('library');if(U.p.ui.left==='materials'){renderMaterialLibrary();return;}host.replaceChildren();
 if(U.p.ui.left==='structure'){
  host.append(el('p','拖动章节调整顺序。将素材拖到章节，即可生成待装配模块。','muted'));
  for(const s of U.p.sections){const card=el('div',s.title,'section-card'+(s.id===U.p.ui.sectionID?' active':''));if(s.parentID)card.style.marginLeft='16px';card.draggable=true;card.dataset.section=s.id;card.ondragstart=e=>e.dataTransfer.setData('application/x-manuscript-section',s.id);card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();const mid=e.dataTransfer.getData('application/x-manuscript-material'),sid=e.dataTransfer.getData('application/x-manuscript-section');snapshot();if(mid){const b=M.block('paragraph',s.id,{assembly:true});attachMaterial(b,mid);U.p.blocks.push(b);U.p.ui.blockID=b.id;}if(sid&&sid!==s.id){const from=U.p.sections.findIndex(x=>x.id===sid),to=U.p.sections.findIndex(x=>x.id===s.id);U.p.sections.splice(to,0,U.p.sections.splice(from,1)[0]);}changed({editor:true});};card.onclick=()=>{U.p.ui.sectionID=s.id;renderEditor();renderLibrary();host.querySelector(`[data-section="${s.id}"]`)?.focus();const page=$('canvas').querySelector(`[data-section="${s.id}"]`);page?.scrollIntoView({block:'start'});U.p.ui.scrollTop=$('canvas').scrollTop;persist();};host.append(card);card.tabIndex=0;for(const b of U.p.blocks.filter(b=>b.sectionID===s.id))outlineBlock(host,b);}
  const more=el('details');more.append(el('summary','章节与 Word 样式'));host.append(more);button('添加章节',()=>{const box=modal('新增章节');const n=field(box,'章节名称','',()=>{});button('添加章节',()=>{if(!n.value.trim())return;snapshot();U.p.sections.push({id:M.id('section'),title:n.value.trim(),conclusion:''});$('popover').close();changed({editor:true});},box);},more);
  button('导入 reference.docx',async()=>{const file=await U.E.pick(window,'选择 Word 样式参考文档','file','docx');if(file){U.p.template.referenceDoc=file;persist();status('已使用参考文档的字体、数学字体、页边距与页眉页脚。');}},more);
  field(more,'正文语言',U.p.language,v=>{U.p.language=v;persist();});
 }else{
  host.append(el('p','绿：已核验 · 黄：缺失或待重核 · 红：冲突。点击节点定位来源与正文。','muted'));
  const order=U.p.ui.evidenceOrder||[];for(const b of [...U.p.blocks].sort((a,b)=>{const rank=id=>order.includes(id)?order.indexOf(id):order.length+U.p.blocks.findIndex(x=>x.id===id);return rank(a.id)-rank(b.id);}))if(b.materials.length)renderEvidence(host,b,true);
  if(!U.p.blocks.some(b=>b.materials.length))host.append(el('p','将素材拖入模块后，这里显示完整证据链。','empty'));
 }
}
export function insertMaterial(m){snapshot();const b=M.block('paragraph',U.p.ui.sectionID||U.p.sections[0].id);attachMaterial(b,m.id);const index=U.p.blocks.findIndex(x=>x.id===U.p.ui.blockID);U.p.blocks.splice(index<0?U.p.blocks.length:index+1,0,b);U.p.ui.blockID=b.id;changed({editor:true});status('已插入素材，来源关联保留 · Ctrl+Z 撤销');}
export function materialDetails(m){U.A.ensureChineseSummaries?.([m]);const box=$('details');box.replaceChildren(el('h3',U.A.titleFor(m)));materialPreview(box,m,U.E);const summary=el('div');U.E.renderContent(summary,U.A.summaryFor(m));box.append(summary);const source=el('details');source.append(el('summary','核对原文与来源'));if(m.sourceText)source.append(el('blockquote',m.sourceText));box.append(source);button('重新整理中文说明',async()=>{await U.A.ensureChineseSummaries([m],{retry:true});materialDetails(m);renderLibrary();},source);button('返回原文或数据',()=>openMaterial(m),source);button('插入正文',()=>{const b=selected();if(!b){insertMaterial(m);return;}snapshot();attachMaterial(b,m.id);changed({editor:true});},box,'primary');button('检查来源更新',()=>refreshMaterial(m),source);if(m.assetID){const edit=el('details');edit.append(el('summary','编辑已积累素材'));box.append(edit);const title=field(edit,'标题',m.title,()=>{}),summary=field(edit,'我的概括',m.summary||'',()=>{},'textarea');button('保存素材新版本',async()=>{const next=await U.A.editAsset(m.assetID,{title:title.value,summary:summary.value},m.revision);Object.assign(m,next);M.invalidate(U.p,m.id);changed();status('素材版本已更新；引用它的模块需要重核。其他项目打开时同步同一素材。');},edit);for(const h of m.history||[])edit.append(el('p',h.at+' · '+h.summary));}}
export async function openMaterial(m,cell){if(m.imagePath){window.parent.Zotero.launchFile(m.imagePath);return;}if(m.anchor?.url){window.parent.Zotero.launchURL(m.anchor.url);return;}if(m.kind==='idea'){status('这是 AI 构想，没有原文证据；请先设计实验验证。');return;}if(m.kind==='abstract'){const box=modal(m.title+' · 仅依据摘要');box.append(el('p',m.fullSourceText||m.sourceText));return;}if(m.data){const box=modal(m.title),t=el('table');for(const [r,row]of m.data.rows.entries()){const tr=el('tr');for(const [c,value]of row.entries()){const td=el(r?'td':'th',value);if(cell?.row===r&&cell?.col===c)td.className='cell-selected';tr.append(td);}t.append(tr);}box.append(t);}else await U.A.openAnchor(m);}
export async function refreshMaterial(m){if(m.aiGenerated){await U.A.checkAssetSource(m);U.A.syncAssets(U.p);changed();status(m.verification==='stale'?'来源已变化；保留原摘录，请重新核验素材。':'来源未变化，保留已积累素材。');return;}const change=await U.A.refreshMaterial(m);if(change&&(change.sourceText!==m.sourceText||change.data?.hash&&change.data.hash!==m.data?.hash)){snapshot();if(m.assetID){Object.assign(m,await U.A.commitAssetSource(m,change));M.invalidate(U.p,m.id);}else M.updateMaterial(U.p,m.id,change);changed({editor:true});status('来源已变化。相关段落需要重新核验；正文未被覆盖。');}else status('来源没有变化，继续使用已保存素材。');}
export function renderEvidence(host,b,sortable=false){const chain=el('div');if(sortable){chain.className='evidence-chain';const grip=el('div','↕ '+(b.title||b.text||'待填写模块').slice(0,40),'evidence-grip');grip.draggable=true;grip.title='上下拖动调整证据阅读顺序，不改变正文';grip.ondragstart=e=>e.dataTransfer.setData('application/x-manuscript-evidence',b.id);chain.append(grip,el('p','来源说明素材，素材支撑段落；章节结论仍需核验。','muted'));chain.ondragover=e=>e.preventDefault();chain.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-manuscript-evidence');if(!id||id===b.id)return;snapshot();const original=[...host.querySelectorAll('[data-evidence]')].map(x=>x.dataset.evidence),to=original.indexOf(b.id),ids=original.filter(x=>x!==id);ids.splice(to,0,id);U.p.ui.evidenceOrder=ids;changed();};}chain.dataset.evidence=b.id;for(const link of b.materials){const m=U.p.materials.find(x=>x.id===link.id);if(!m)continue;button(m.kind==='experiment'?'▦ 实验数据':m.anchor.attachmentID?`▤ PDF 原文 · 第 ${(m.anchor.pageIndex||0)+1} 页`:'▤ Zotero 笔记',()=>openMaterial(m),chain,'evidence-node '+b.review);chain.append(el('div','↓','arrow'));button(m.title,()=>materialDetails(m),chain,'evidence-node '+b.review);}chain.append(el('div','↓','arrow'));button((b.type==='table'?'▦ 表格：':'¶ 段落：')+(b.text||b.table?.caption||'待填写').slice(0,45),()=>selectBlock(b.id,{scroll:true}),chain,'evidence-node '+b.review);chain.append(el('div','↓','arrow'));const section=U.p.sections.find(s=>s.id===b.sectionID);button('章节结论 · '+(section?.conclusion||'尚未核验'),()=>{U.p.ui.sectionID=b.sectionID;const box=modal('章节结论');field(box,'结论（请核对本章节来源）',section.conclusion,v=>{section.conclusion=v;changed();},'textarea');},chain,'evidence-node '+(section?.conclusion?b.review:'missing'));host.append(chain);}
export async function pickMaterials(){
 const box=modal('选择素材');box.append(el('p','选择论文后勾选笔记与批注；所有来源保留在 Zotero。自己的实验可单独加入。'));
 const row=el('div',undefined,'row');box.append(row);
 button('导入 CSV / XLSX',async()=>{const f=await U.E.pick(window,'选择实验数据','file','csv;xlsx');if(!f)return;await importData(f);$('popover').close();},row);
 button('添加实验记录',()=>{const x=el('section');box.append(x);const name=field(x,'记录名称','我的实验',()=>{}),text=field(x,'实验设置、观察、失败原因或计划','',()=>{},'textarea');button('保存为实验素材',async()=>{if(!text.value.trim())throw Error('请先填写实验记录');snapshot();const saved=await U.A.publishMaterials([M.material({title:name.value,kind:'experiment',sourceText:text.value,anchor:{sourceText:text.value}})]);if(!U.p.materials.some(m=>m.id===saved.cards[0].id))U.p.materials.push(saved.cards[0]);changed();$('popover').close();},x);},row);
 const papers=await U.A.papers(),picker=el('details');picker.open=!(U.p.materialPaperIDs?.length);picker.append(el('summary','选择论文 · 可多选'));box.append(picker);
 const search=el('input');search.placeholder='按论文标题搜索';search.setAttribute('aria-label','搜索来源论文');picker.append(search);const paperList=el('div');paperList.style.maxHeight='180px';paperList.style.overflow='auto';picker.append(paperList);
 const cards=el('div');box.append(cards);let generation=0;U.p.materialPaperIDs||=[];
 const has=m=>U.p.materials.some(x=>m.sourceItemID?x.sourceItemID===m.sourceItemID:m.sourceRecordID?x.sourceRecordID===m.sourceRecordID:false);
 const load=async()=>{const token=++generation;const candidates=await U.A.candidates(U.p.materialPaperIDs);if(token!==generation)return;cards.replaceChildren();const experiments=el('details');experiments.append(el('summary','已有个人实验记录'));let count=0;
  for(const m of candidates){const label=el('label'),input=el('input');input.type='checkbox';input.dataset.sourceItem=m.sourceItemID||'';input.checked=has(m);label.append(input,document.createTextNode(m.title+' · '+m.sourceText.slice(0,85)));input.onchange=async()=>{try{input.disabled=true;if(input.checked&&!has(m)){const saved=await U.A.publishMaterials([m]);snapshot();if(!U.p.materials.some(m=>m.id===saved.cards[0].id))U.p.materials.push(saved.cards[0]);changed();}else if(!input.checked&&has(m)){const existing=U.p.materials.find(x=>m.sourceItemID?x.sourceItemID===m.sourceItemID:x.sourceRecordID===m.sourceRecordID);if(U.p.blocks.some(b=>b.materials.some(x=>x.id===existing.id))){input.checked=true;status('此素材已用于正文，请先解除模块关联。');}else{snapshot();U.p.materials=U.p.materials.filter(x=>x.id!==existing.id);changed();}}}catch(e){status(e.message,true);input.checked=has(m);}finally{input.disabled=false;}};if(m.kind==='experiment')experiments.append(label);else{cards.append(label);count++;}}
  if(!count)cards.append(el('p',U.p.materialPaperIDs.length?'选中论文暂无笔记或批注。可先阅读并标注，或加入自己的实验。':'请选择一篇或多篇论文，查看可用笔记与批注。','empty'));if(experiments.children.length>1)cards.append(experiments);
 };
 const renderPapers=()=>{paperList.replaceChildren();for(const paper of papers.filter(p=>p.title.toLowerCase().includes(search.value.toLowerCase()))){const label=el('label'),input=el('input');input.type='checkbox';input.dataset.paper=paper.id;input.checked=U.p.materialPaperIDs.includes(paper.id);label.append(input,document.createTextNode(paper.title));input.onchange=()=>{U.p.materialPaperIDs=U.p.materialPaperIDs.filter(id=>id!==paper.id);if(input.checked)U.p.materialPaperIDs.push(paper.id);persist();load().catch(e=>status(e.message,true));};paperList.append(label);}};search.oninput=renderPapers;renderPapers();await load();
 button('完成选择，开始装配',()=>{U.p.ui.step=1;changed();$('popover').close();},box);
}
export async function importData(file){const data=await U.A.dataset(file);const m=M.material({title:data.sheet,kind:'experiment',file,sourceText:JSON.stringify(data.rows),data,anchor:{sourceText:JSON.stringify(data.rows)}});const saved=await U.A.publishMaterials([m]),existing=U.p.materials.find(m=>m.id===saved.cards[0].id);if(existing)return existing;snapshot();U.p.materials.push(saved.cards[0]);changed();return saved.cards[0];}
export async function verifyBlock(b){if(!b)throw Error('请选择需要核验的模块');const box=modal('逐条核对当前模块');box.append(el('p','已核验表示你已对照来源检查内容；AI 摘录匹配不等同于结论成立。'));renderEvidence(box,b);for(const e of b.evidence||[]){const m=U.p.materials.find(m=>m.id===e.materialID);button('核对摘录：'+e.quote,()=>openMaterial(m,e.cell),box);}button('来源支持当前内容，标记已核验',()=>{if(b.materials.some(x=>U.p.materials.find(m=>m.id===x.id)?.kind==='idea'))throw Error('构想素材尚未验证，不能标为已核验');if(b.claim&&!b.materials.length)throw Error('该论点还没有来源');for(const x of b.materials)x.revision=U.p.materials.find(m=>m.id===x.id)?.revision;b.review='verified';changed({editor:true});$('popover').close();},box);button('发现冲突',()=>{b.review='conflict';changed({editor:true});$('popover').close();},box);}
export async function check(){const issues=await U.A.check(U.p);const box=modal('导出前检查');box.append(el('p',issues.length?`${issues.length} 项内容需要处理`:'结构检查通过。请继续核对论证和版式。'));for(const issue of issues)button(issue.message,()=>{$('popover').close();selectBlock(issue.blockID,{scroll:true});},box);return issues;}
export async function exportDoc(preview){if(U.busy)throw Error('当前任务仍在执行');await persist();if(U.saveError)throw U.saveError;const issues=await U.A.check(U.p);if(issues.length){await check();return;}const folder=preview?null:await U.E.pick(window,'选择 DOCX 导出目录','folder');if(!preview&&!folder)return;U.busy=true;U.abort=new AbortController();status('正在生成 Word 文档并检查公式与表格…');$('cancel-ai').hidden=false;$('cancel-task').hidden=false;try{U.lastExport=await(preview?U.A.preview(U.p,status,U.abort.signal):U.A.export(U.p,folder,status,U.abort.signal));status('已导出 Word 文档：'+U.lastExport.path);}finally{U.busy=false;$('cancel-ai').hidden=true;$('cancel-task').hidden=true;}}
async function aiSubmit(e){
 e.preventDefault();const input=$('ai-prompt'),submitted=input.value,prompt=submitted.trim();if(!prompt||U.busy||U.aiSending)return;
 const mode=resolveMode($('ai-mode').value,prompt,'write');U.aiSending=true;$('ask-ai').disabled=true;$('ai-mode').disabled=true;$('ai-notice').hidden=true;
 const clearSentDraft=()=>{if(input.value!==submitted)return;input.value='';input.style.height='';U.p.ui.aiDraft='';persist();};
 const report=(text,error=false)=>{status(text,error);if(U.aiActivity)U.aiActivity.textContent=text;};
 try{
  const templates=$('ai-form').querySelector('.prompt-templates');if(templates)templates.hidden=true;
  if(mode==='search'){
   U.materialQuery=prompt;U.p.ui.left='materials';U.p.ui.leftOpen=true;await U.E.notebook.update(U.p.id,{query:prompt});applyPanels();renderNavigation();status('已检索本地素材，选择结果预览或插入正文。');return;
  }
  if(mode==='write'){const count=U.p.proposals.length;await completeBlock(prompt);if(U.p.proposals.length>count)clearSentDraft();return;}
  U.busy=true;U.abort=new AbortController();$('cancel-ai').hidden=false;
  U.p.chat.push({role:'user',text:prompt,at:new Date().toISOString()});renderChat();
  U.aiActivity=el('div','正在查找相关来源…','coauthor-activity');U.aiActivity.setAttribute('role','status');$('chat').after(U.aiActivity);await persist();
  if(mode==='evaluate'){
   const v=await U.E.notebook.evaluate(U.p.id,prompt,report,U.abort.signal),box=$('diff');box.replaceChildren(el('h3','Idea 与可行性 · 第 '+v.number+' 版'));const content=el('div');box.append(content);U.E.renderContent(content,U.E.notebook.planMarkdown(v),{sources:v.sources,onSource:s=>U.E.notebook.openSource(s)});button('确认并加入素材库',()=>U.E.notebook.confirm(U.p.id,v.id),box);
   status('方案已保存为新版本，仍是待验证的实验计划。');
  }else{
   const answer=await U.E.notebook.ask(U.p.id,prompt,report,U.abort.signal);U.p.chat.push({role:'assistant',text:answer.text,sources:answer.sources,at:new Date().toISOString()});renderChat();status('讨论已保存。');
  }
  clearSentDraft();await persist();
 }catch(err){status(err.message||'暂时未能完成，请重试。',true);}
 finally{U.aiSending=false;U.busy=false;U.aiActivity?.remove();U.aiActivity=null;$('ask-ai').disabled=false;$('ai-mode').disabled=false;$('cancel-ai').hidden=true;}
}
export function renderChat(){
 const current=selected();$('ai-context').textContent=current?'当前段落'+(current.materials.length?' · '+current.materials.length+' 个来源':' · 可检索素材库'):U.p.title;
 const signature=JSON.stringify(U.p.chat);if(U.chatRendered===signature)return;U.chatRendered=signature;$('chat').replaceChildren();
 for(const c of U.p.chat){const row=el('article',undefined,'coauthor-message '+(c.role==='user'?'from-user':'from-assistant')),body=el('div'),meta=el('div',undefined,'message-meta');meta.append(el('span',c.role==='user'?'你':'AI 共创'));if(c.at){const date=new Date(c.at);if(!isNaN(date))meta.append(el('time',date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})));}row.append(meta,body);U.E.renderContent(body,c.text,{sources:c.sources||[],onSource:s=>U.E.notebook.openSource(s)});$('chat').append(row);}
 if(!U.p.chat.length){const empty=el('div',undefined,'coauthor-empty');empty.append(el('strong','围绕这篇论文，一起推进'),el('p','直接提问，或选中一段正文。素材与来源会按需带入。'));$('chat').append(empty);}
 requestAnimationFrame(()=>{$('ai-history').scrollTop=$('ai-history').scrollHeight;});
}
export function showDiff(d,{reveal=true}={}){if(reveal){U.p.ui.aiOpen=true;U.p.ui.aiHeight=Math.max(U.p.ui.aiHeight,340);applyPanels();}const box=$('diff');box.replaceChildren(el('h3','修改建议 · 确认前不会写入正文'));const cols=el('div',undefined,'diff-columns');cols.append(el('div',d.before||'（空模块）','diff-before'),el('div',d.after,'diff-after'));box.append(cols);if(d.toolTrace?.length){const log=el('details');log.append(el('summary','本次 AI 调用记录'));for(const t of d.toolTrace)log.append(el('p',t.name+' · '+JSON.stringify(t.arguments||{})));box.append(log);}for(const e of d.evidence){const m=U.p.materials.find(m=>m.id===e.materialID)||d.retrievedMaterials?.find(m=>m.id===e.materialID);button('来源：'+e.quote,()=>openMaterial(m,e.cell),box);}button('确认应用到当前模块',()=>{const candidate=M.clone(U.p);for(const m of d.retrievedMaterials||[]){const current=U.A.assetLibrary()[m.assetID];if(current&&current.revision!==m.revision)throw Error('检索素材已有新版本，请重新补全');if(!candidate.materials.some(x=>x.id===m.id))candidate.materials.push(M.clone(m));const block=candidate.blocks.find(x=>x.id===d.blockID);if(!block.materials.some(x=>x.id===m.id))block.materials.push({id:m.id,role:'support',revision:m.revision});}M.applyProposal(candidate,M.clone(d));snapshot();for(const m of candidate.materials)if(!U.p.materials.some(x=>x.id===m.id))U.p.materials.push(m);U.p.blocks.find(x=>x.id===d.blockID).materials=candidate.blocks.find(x=>x.id===d.blockID).materials;M.applyProposal(U.p,d);changed({editor:true});box.replaceChildren(el('p','已应用。可按 Ctrl+Z 撤销；请核验结论。'));},box);button('保留原文',()=>{d.status='rejected';persist();box.replaceChildren();},box);requestAnimationFrame(()=>{$('ai-history').scrollTop=box.offsetTop-$('ai-history').offsetTop;});}
function renderAssessment(){const a=U.E.notebook.state(U.p.id).assessment;let box=$('assessment-inline');if(!a)return;if(!box){box=el('div');box.id='assessment-inline';$('tools').after(box);}box.replaceChildren(el('span',a.status==='running'?'正在评估研究可行性，可继续写作…':a.message||'可行性评估待处理'));if(a.status==='ready')button('查看可行性方案',()=>{const v=U.E.notebook.state(U.p.id).versions.find(v=>v.id===a.versionID),host=modal('研究可行性与实验方案');if(v){const body=el('div');U.E.renderContent(body,U.E.notebook.planMarkdown(v),{sources:v.sources,onSource:s=>U.E.notebook.openSource(s)});host.append(body);}},box);if(a.status==='running')button('停止',()=>U.E.notebook.cancelAssessment(U.p.id),box);if(a.status==='failed')button('重试评估',()=>U.E.notebook.startAssessment(U.p.id),box);}
async function init(){U.A=U.E.manuscripts;const id=window.frameElement.manuscriptID;U.p=M.clone(U.A.get(id));if((U.p.ui.surfaceVersion||0)<2){if(!U.p.ui.leftWidth||U.p.ui.leftWidth<=310)U.p.ui.leftWidth=380;U.p.ui.surfaceVersion=2;}U.savedRevision=U.p.revision;window.ManuscriptUI=U;U.materialQuery=U.E.notebook.query(id)||'';U.unsubscribeNotebook=U.E.notebook.subscribe(projectID=>{if(projectID!==id)return;renderAssessment();const state=U.E.notebook.state(id);if(U.materialView!==state.materialView){U.materialView=state.materialView;renderLibrary();}if(U.materialQuery!==state.query){U.materialQuery=state.query||'';const input=$('material-search');if(input&&document.activeElement!==input)input.value=U.materialQuery;renderLibrary();}if(!U.clearingMaterialSelection&&state.selectedMaterial&&U.previewMaterialID!==state.selectedMaterial){U.previewMaterialID=state.selectedMaterial;U.p.ui.materialID=state.selectedMaterial;if(U.p.ui.catalog&&!U.p.ui.catalog.selection?.includes(state.selectedMaterial))U.p.ui.catalog.selection=[state.selectedMaterial];renderLibrary();const m=U.A.assetLibrary()[state.selectedMaterial]||U.p.materials.find(m=>m.id===state.selectedMaterial);if(m)materialDetails(m);}});Object.assign(U,{persist,importData,renderEditor,selectBlock,changed,insertBlock,renderLibrary,exportDoc,insertMaterial});
 $('close-popover').onclick=()=>$('popover').close();$('toggle-left').onclick=()=>{U.p.ui.leftOpen=!U.p.ui.leftOpen;applyPanels();persist();};$('toggle-right').onclick=()=>{U.p.ui.rightOpen=!U.p.ui.rightOpen;applyPanels();persist();};$('collapse-chat').onclick=closeCoauthor;$('toggle-ai').onclick=()=>U.p.ui.aiOpen?closeCoauthor():openCoauthor();$('check').onclick=()=>check().catch(e=>status(e.message,true));$('preview').onclick=()=>exportDoc(true).catch(e=>status(e.message,true));$('export').onclick=()=>exportDoc(false).catch(e=>status(e.message,true));$('cancel-ai').onclick=$('cancel-task').onclick=()=>U.abort?.abort();document.querySelector('.ai-collapsed-name').onclick=()=>{openCoauthor();$('ai-prompt').focus();};$('ai-form').onsubmit=aiSubmit;$('ai-prompt').value=U.p.ui.aiDraft||'';$('ai-prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.ctrlKey&&!e.altKey&&!e.isComposing&&!U.composing&&e.keyCode!==229){e.preventDefault();$('ai-form').requestSubmit();}});$('ai-prompt').addEventListener('input',()=>{$('ai-prompt').style.height='auto';$('ai-prompt').style.height=Math.min(100,$('ai-prompt').scrollHeight)+'px';U.p.ui.aiDraft=$('ai-prompt').value;persist();});$('ai-prompt').addEventListener('focus',openCoauthor);$('ai-prompt').addEventListener('pointerdown',openCoauthor);installModePicker($('ai-mode'),$('ai-prompt'),{value:U.E.notebook.state(id).aiMode,onChange:aiMode=>U.E.notebook.update(id,{aiMode})});
 for(const [name,fn]of [['引用',()=>insertBlock('citation')],['公式',()=>insertBlock('formula')],['表格',tablePicker],['图片',()=>insertBlock('image')],['论文模块',()=>{const box=modal('选择论文模块');for(const [type,name]of [['paragraph','正文'],['heading','小标题'],['list','列表'],['placeholder','待填内容卡']])button(name,()=>{insertBlock(type);$('popover').close();},box);}]])button(name,fn,$('insert-tools'));
 let scrollTimer;$('canvas').onscroll=()=>{U.p.ui.scrollTop=$('canvas').scrollTop;clearTimeout(scrollTimer);scrollTimer=setTimeout(persist,180);};
 installKeyboard();installAssembly();installEditorInteractions();installPromptTemplates(document,U.E);
 for(const grip of document.querySelectorAll('[data-panel],.ai-grip'))grip.onpointerdown=e=>{const key=grip.dataset.panel||'aiHeight',start=key==='aiHeight'?e.clientY:e.clientX,value=U.p.ui[key];grip.setPointerCapture(e.pointerId);grip.onpointermove=e=>{U.p.ui[key]=Math.max(key==='aiHeight'?130:190,Math.min(600,value+((key==='leftWidth'?1:-1)*((key==='aiHeight'?e.clientY:e.clientX)-start))));applyPanels();};grip.onpointerup=()=>{grip.onpointermove=null;persist();};};
 applyPanels();renderNavigation();renderEditor();renderChat();renderAssessment();const pending=U.p.proposals.findLast(d=>d.status==='pending');if(pending)showDiff(pending,{reveal:false});$('canvas').scrollTop=U.p.ui.scrollTop;status('已恢复项目。先选素材，或继续编辑当前模块。');U.ready=true;if(['queued','running'].includes(U.E.notebook.state(id).assessment?.status))U.E.notebook.startAssessment(id).catch(e=>status(e.message,true));const pendingPrompt=U.E.notebook.state(id).writingPrompt;if(pendingPrompt){$('ai-prompt').value=pendingPrompt;U.p.ui.aiOpen=true;applyPanels();U.E.notebook.update(id,{writingPrompt:''});}U.unsubscribeAssets=U.A.onAssetsChanged?.(()=>{U.A.syncAssets(U.p);renderLibrary();const selectedMaterial=U.A.assetLibrary()[U.previewMaterialID];if(selectedMaterial)materialDetails(selectedMaterial);persist();});
 window.addEventListener('pagehide',()=>{U.unsubscribeAssets?.();U.unsubscribeNotebook?.();if(!U.closing)persist();});window.addEventListener('focus',async()=>{U.A.syncAssets(U.p);for(const m of U.p.materials.filter(m=>m.aiGenerated&&m.assetID)){try{await U.A.checkAssetSource(m);}catch(e){M.invalidate(U.p,m.id);status(e.message,true);}}U.A.syncAssets(U.p);for(const m of U.p.materials.filter(m=>!m.aiGenerated&&(m.file||m.sourceItemID))){try{await refreshMaterial(m);}catch(e){status(e.message,true);}}});
}
init().catch(e=>status('论文装配未能打开：'+e.message,true));
