/* SPDX-License-Identifier: AGPL-3.0-or-later */
import {U,$,el,button,field,modal,status,snapshot,changed,persist,selectBlock,importData} from './main.mjs';
import {insertBlock} from './editor.mjs';
export function tablePicker(){const box=modal('插入表格'),hint=el('p','移动鼠标选择行列，例如 4 列 × 3 行'),grid=el('div');grid.id='grid';box.append(hint,grid);for(let r=1;r<=8;r++)for(let c=1;c<=8;c++){const b=button('',()=>{insertBlock('table',{table:U.M.makeTable(r,c)});$('popover').close();},grid);b.dataset.row=r;b.dataset.col=c;b.title=`${r} 行 ${c} 列`;b.setAttribute('aria-label',b.title);b.onmouseover=b.onfocus=()=>{hint.textContent=`${c} 列 × ${r} 行`;for(const cell of grid.children)cell.classList.toggle('highlight',+cell.dataset.row<=r&&+cell.dataset.col<=c);};}
 const advanced=el('details');advanced.append(el('summary','需要更大的表格'));box.append(advanced);const rows=field(advanced,'行数',10,()=>{}),cols=field(advanced,'列数',5,()=>{});rows.type=cols.type='number';button('插入自定义表格',()=>{insertBlock('table',{table:U.M.makeTable(+rows.value,+cols.value)});$('popover').close();},advanced);
}
function addRow(b){snapshot();b.table.rows.push(b.table.widths.map(()=>({text:'',rowspan:1,colspan:1,align:'auto',vertical:'center'})));b.table.heights.push(9);changed({editor:true});}
function addCol(b){snapshot();b.table.rows.forEach((r,i)=>r.push({text:i?'':'新列',rowspan:1,colspan:1,align:'auto',vertical:'center'}));b.table.widths.push(30);const sum=b.table.widths.reduce((a,b)=>a+b);b.table.widths=b.table.widths.map(w=>w/sum*b.table.width);changed({editor:true});}
function drag(grip,b,apply){grip.onpointerdown=e=>{e.stopPropagation();e.preventDefault();snapshot();const x=e.clientX,y=e.clientY,original=U.M.clone(b.table);grip.setPointerCapture(e.pointerId);grip.onpointermove=e=>{apply((e.clientX-x)/(U.p.ui.paperZoom||1),(e.clientY-y)/(U.p.ui.paperZoom||1),original);const node=grip.closest('.table-wrap');node.querySelector('table').style.width=b.table.width+'mm';node.querySelectorAll('col').forEach((col,i)=>col.style.width=b.table.widths[i]+'mm');node.querySelectorAll('tr').forEach((tr,i)=>tr.style.height=b.table.heights[i]+'mm');};grip.onpointerup=()=>{grip.onpointermove=null;changed({editor:true});};};}
export function renderTable(host,b){const spec=b.table,wrap=el('div',undefined,'table-wrap'),caption=el('div',`表 ${U.p.blocks.filter(x=>x.type==='table').indexOf(b)+1} ${spec.caption||'（点击右侧补充表题）'}`);wrap.append(caption);const table=el('table');table.style.width=spec.width+'mm';const group=el('colgroup');spec.widths.forEach(w=>{const col=el('col');col.style.width=w+'mm';group.append(col);});table.append(group);
 spec.rows.forEach((row,r)=>{const tr=el('tr');tr.style.height=spec.heights[r]+'mm';row.forEach((cell,c)=>{if(cell.hidden)return;const td=el(r?'td':'th');td.rowSpan=cell.rowspan;td.colSpan=cell.colspan;td.dataset.row=r;td.dataset.col=c;td.style.verticalAlign=cell.vertical;td.style.padding=spec.padding+'mm';td.style.border=`${spec.border}pt solid #${spec.color}`;if(spec.style==='three-line'){td.style.border='none';if(r===0)td.style.borderTop=td.style.borderBottom=`${spec.border}pt solid #${spec.color}`;if(r+cell.rowspan===spec.rows.length)td.style.borderBottom=`${spec.border}pt solid #${spec.color}`;}
 const alignment=cell.align==='auto'?(r===0||/^[-+]?\d[\d.,% ±Ee-]*$/.test(cell.text.trim())?'center':'left'):cell.align;td.style.textAlign=alignment;
 const input=el('div',cell.text,'cell-editor');input.contentEditable=true;input.setAttribute('aria-label',`第 ${r+1} 行第 ${c+1} 列`);input.onbeforeinput=()=>{if(!U.lastTyping||Date.now()-U.lastTyping>1000)snapshot();U.lastTyping=Date.now();};input.oninput=()=>{cell.text=input.innerText;if(spec.binding)b.review='stale';b.revision++;for(const downstream of U.p.blocks)if(downstream.dependsOn?.includes(b.id))downstream.review='stale';persist();};input.onpaste=e=>{e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));};
 td.onclick=e=>{e.stopPropagation();if(U.p.ui.blockID!==b.id){U.selectedCells=[];selectBlock(b.id);}if(e.shiftKey&&U.selectedCells.length){const first=U.selectedCells[0];U.selectedCells=[];for(let rr=Math.min(first.r,r);rr<=Math.max(first.r,r);rr++)for(let cc=Math.min(first.c,c);cc<=Math.max(first.c,c);cc++)U.selectedCells.push({r:rr,c:cc});}else U.selectedCells=[{r,c}];for(const n of table.querySelectorAll('td,th'))n.classList.toggle('cell-selected',U.selectedCells.some(x=>x.r===+n.dataset.row&&x.c===+n.dataset.col));U.p.ui.cell={r,c};persist();};td.append(input);
 if(r===0){const resize=el('span',undefined,'col-resize');td.append(resize);drag(resize,b,(dx,dy,old)=>{const next=Math.max(8,old.widths[c]+dx/3.78);const delta=next-old.widths[c];b.table.widths[c]=next;b.table.width=old.width+delta;});}
 if(c===0){const resize=el('span',undefined,'row-resize');td.append(resize);drag(resize,b,(dx,dy,old)=>b.table.heights[r]=Math.max(6,old.heights[r]+dy/3.78));}
 tr.append(td);});table.append(tr);});wrap.append(table);button('+',()=>addRow(b),wrap,'table-add row-add').title='在表格下方添加一行';button('+',()=>addCol(b),wrap,'table-add col-add').title='在右侧添加一列';const resize=el('span',undefined,'table-resize');wrap.append(resize);drag(resize,b,(dx,dy,old)=>{b.table.width=Math.max(50,Math.min(170,old.width+dx/3.78));b.table.widths=old.widths.map(w=>w*b.table.width/old.width);});host.append(wrap);}
export function mergeCells(b){const cells=U.selectedCells;if(cells.length<2)throw Error('按住 Shift 点击另一单元格，选择一个矩形区域后合并');const r0=Math.min(...cells.map(x=>x.r)),r1=Math.max(...cells.map(x=>x.r)),c0=Math.min(...cells.map(x=>x.c)),c1=Math.max(...cells.map(x=>x.c));for(let r=r0;r<=r1;r++)for(let c=c0;c<=c1;c++){const x=b.table.rows[r][c];if(x.hidden||x.rowspan>1||x.colspan>1)throw Error('请先拆分已有合并单元格');}snapshot();const text=[];for(let r=r0;r<=r1;r++)for(let c=c0;c<=c1;c++){const cell=b.table.rows[r][c];if(cell.text)text.push(cell.text);cell.hidden=true;}Object.assign(b.table.rows[r0][c0],{hidden:false,rowspan:r1-r0+1,colspan:c1-c0+1,text:text.join(' ')});U.selectedCells=[];changed({editor:true});}
export function tableDetails(host,b){const row=el('div',undefined,'row');button('＋ 行',()=>addRow(b),row);button('＋ 列',()=>addCol(b),row);button('合并单元格',()=>mergeCells(b),row);host.append(row,el('p','Shift + 点击选择多个单元格；拖动表格边缘可调整尺寸。','muted'));
 const align=el('div',undefined,'row');for(const [key,name]of [['left','左对齐'],['center','居中'],['right','右对齐']])button(name,()=>{if(!U.selectedCells.length)throw Error('先选择单元格');snapshot();for(const x of U.selectedCells)b.table.rows[x.r][x.c].align=key;changed({editor:true});},align);host.append(align);
 const styles=el('div',undefined,'row');for(const [key,name]of [['grid','完整边框'],['three-line','学术三线表']])button(name,()=>{snapshot();b.table.style=key;changed({editor:true});},styles,b.table.style===key?'active':'');host.append(styles);field(host,'表题',b.table.caption,v=>{b.table.caption=v;changed({editor:true});});
 const binding=el('details');binding.open=!!b.table.binding;binding.append(el('summary',b.table.binding?'已绑定实验数据':'绑定 CSV / XLSX 或实验素材'));host.append(binding);
 const bind=m=>{snapshot();U.M.bindTable(U.p,b,m);changed({editor:true});status('表格已绑定数据。来源更新会标记正文待核验。');};for(const m of U.p.materials.filter(m=>m.data))button(m.title,()=>bind(m),binding);
 button('从文件选择数据',async()=>{const file=await U.E.pick(window,'选择实验数据','file','csv;xlsx');if(file)bind(await importData(file));},binding);
 if(b.table.binding)button('用当前来源更新表格',()=>{const m=U.p.materials.find(m=>m.id===b.table.binding.materialID);bind(m);U.M.invalidate(U.p,m.id);changed({editor:true});},binding);
 button('在表后添加分析段落',()=>insertBlock('paragraph',{dependsOn:[b.id],materials:U.M.clone(b.materials),claim:true}),binding);
 const more=el('details');more.append(el('summary','高级格式'));host.append(more);for(const [key,label]of [['border','线宽（pt）'],['padding','单元格边距（mm）']]){const i=field(more,label,b.table[key],v=>{b.table[key]=Math.min(8,Math.max(.1,Number(v)||1));changed({editor:true});});i.type='number';i.step='.1';}const color=field(more,'边框颜色','#'+b.table.color,v=>{b.table.color=v.replace('#','');changed({editor:true});});color.type='color';
 const vertical=el('div',undefined,'row');for(const [key,name]of [['top','顶部'],['center','垂直居中'],['bottom','底部']])button(name,()=>{snapshot();for(const x of U.selectedCells)b.table.rows[x.r][x.c].vertical=key;changed({editor:true});},vertical);more.append(vertical);
 button('拆分选中合并单元格',()=>{const x=U.selectedCells[0];if(!x)throw Error('先选中合并单元格');snapshot();const cell=b.table.rows[x.r][x.c];for(let r=x.r;r<x.r+cell.rowspan;r++)for(let c=x.c;c<x.c+cell.colspan;c++)b.table.rows[r][c].hidden=false;cell.rowspan=cell.colspan=1;changed({editor:true});},more);
 button('插入此表的交叉引用',()=>insertBlock('crossref',{targetID:b.id,text:'表 '+(U.p.blocks.filter(x=>x.type==='table').indexOf(b)+1)}),more);
}
