import {U,$,el,button,field,modal,status,snapshot,changed,persist,selected,showDiff,renderChat,attachMaterial,openMaterial,applyPanels} from './main.mjs';
export async function themeLibrary(initial=''){
 const box=modal('建立主题素材库');box.append(el('p','先检索你的文库，再整理候选卡。原文证据与 AI 构想分开显示，确认后才加入长期素材。'));
 const topic=field(box,'研究主题或要求',initial||U.p.memory?.goal||'',()=>{},'textarea');topic.id='topic-prompt';topic.placeholder='围绕少样本跨域调制识别，整理背景、方法、基线和待验证方向';
 const options=el('details');options.append(el('summary','检索范围与已积累素材'));box.append(options);const label=el('label'),external=el('input');external.type='checkbox';label.append(external,document.createTextNode('同时检索外部论文摘要（arXiv）'));options.append(label);for(const m of Object.values(U.A.assetLibrary()))button('复用 · '+m.title,()=>{if(!U.p.materials.some(x=>x.id===m.id)){snapshot();U.p.materials.push(m);changed();}status('已关联已有素材，保留同一来源 ID。');},options);
 const progress=el('p','优先使用本项目已选论文及文库中与主题匹配的资料。','muted'),results=el('div');results.id='topic-results';box.append(progress,results);
 const cancel=button('取消素材整理',()=>{U.abort?.abort();progress.textContent='正在取消，已确认素材不会删除。';},box);cancel.hidden=true;cancel.id='cancel-topic';
 const start=button('检索并整理素材',async()=>{if(U.busy)throw Error('请先完成当前任务');if(!topic.value.trim())throw Error('请输入研究主题');U.busy=true;U.abort=new AbortController();$('cancel-task').hidden=false;start.disabled=true;cancel.hidden=false;results.replaceChildren();try{const response=await U.A.buildTopic(U.p,topic.value,t=>{progress.textContent=t;status(t);},U.abort.signal,external.checked);start.classList.remove('primary');const chosen=new Set(response.cards);progress.textContent=`找到 ${response.sources.length} 份材料；候选证据 ${response.cards.filter(m=>m.kind!=='idea').length} 张，待验证构想 ${response.cards.filter(m=>m.kind==='idea').length} 张。${response.cacheHit?'（复用 AI 分析缓存）':''}`;
 for(const m of response.cards){const card=el('article',undefined,'theme-card'),check=el('input');check.type='checkbox';check.checked=true;check.onchange=()=>check.checked?chosen.add(m):chosen.delete(m);const head=el('label');head.append(check,document.createTextNode(m.title));card.append(head,el('small',m.kind==='idea'?'AI 构想 · 待验证':m.coverage||(m.kind==='note'?'Zotero 笔记 · 个人理解':m.kind==='experiment'?'用户实验记录':'PDF 原文')+' · 概括待核验'),el('p',m.summary));if(m.sourceText){card.append(el('blockquote',m.sourceText));button('核对来源',()=>openMaterial(m),card);}results.append(card);}
 button('确认加入主题素材库',async()=>{const saved=await U.A.publishMaterials([...chosen]);snapshot();for(const m of saved.cards)if(!U.p.materials.some(x=>x.id===m.id))U.p.materials.push(m);U.p.memory||={decisions:[],terms:[],questions:[]};U.p.memory.goal=topic.value;changed();$('popover').close();status(`新增 ${saved.added} 张，复用 ${saved.reused} 张；AI 概括与构想均保留待核验标识。`);},results,'primary');
 }catch(e){start.classList.add('primary');progress.textContent='未加入素材：'+e.message+'。可修改主题后重试。';status(e.message,true);}finally{U.busy=false;cancel.hidden=true;start.disabled=false;$('cancel-task').hidden=true;}},box,'primary');start.id='build-topic';
}
export async function paragraphAction(purpose){const b=selected(),selection=U.textSelection?.blockID===b?.id?U.textSelection:null;if(!b)throw Error('请先选择段落');if(b.locked)throw Error('此段已锁定，请先解锁');if(purpose==='evidence'){await themeLibrary((U.p.sections.find(s=>s.id===b.sectionID)?.title||'')+' '+b.text.slice(0,180));return;}if(U.busy)throw Error('当前任务仍在执行');U.p.ui.aiOpen=true;applyPanels();U.busy=true;U.abort=new AbortController();$('cancel-task').hidden=false;const names={polish:'润色',shorten:'精简',expand:'扩写',restructure:'重组',translate:'翻译',terms:'解释术语'};U.p.chat.push({role:'user',text:names[purpose]+'当前模块',blockID:b.id});renderChat();persist();try{const d=await U.A.rewrite(U.p,b.id,purpose,status,U.abort.signal,selection);if(U.abort.signal.aborted)throw Error('已取消');U.p.proposals.push(d);U.p.chat.push({role:'assistant',text:d.after,blockID:b.id});persist();renderChat();showDiff(d);}finally{U.busy=false;$('cancel-task').hidden=true;}}
